[lenaios] Step1 - Drinkable Protocol과 Protocol을 채택하는 음료 Class 정의
code-squad/swift-vendingmachineapp pull request #226
Opened 2021-02-23 11:35 UTC by lenaios

### 작업 목록
- [x] Milk, Coffee, Soda 클래스를 정의하고, 공통 속성을 Drinkable Protocol로 추상화
- [x] Date 타입을 String 타입으로 출력하기 위해, DateFormatter를 Utility 객체의 static func으로 정의
- [x] VendingMachine이 음료 객체의 배열을 속성으로 갖고 있지 않도록 Drinks 타입을 하위 모듈로 생성
- [x] ViewController 내에서 Milk, Coffee, Soda 객체를 생성하고, closure를 사용해서 drinks 출력

### 학습 키워드
- Protocol, Extension

### 고민과 해결
객체를 추상화하는 방법으로 상속과 프로토콜을 사용하는 방법 중, 프로토콜을 선택했습니다. 그 이유는 상속은 수직적 확장인 반면, 프로토콜은 수평적인 확장이라는 점에서 상속보다 유연하다고 판단했기 때문입니다.
그 과정에서 프로토콜, 프로토콜과 상속의 차이, 프로토콜과 (다른 언어의) 인터페이스와의 차이를 학습하고 사용하였습니다.

2021-02-23 12:19 UTC, godrm requested changes
다음 피드백을 확인하고 개선해보세요.

2021-02-23 12:19 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AppDelegate.swift
> +        // Use this method to select a configuration to create the new scene with.
이전 단계에서 했던 피드백을 최대한 적용해보세요.
프로젝트 템플릿으로 자동 생성되는 함수나 주석 등은 직접 사용하지 않는 경우는 과감하게 지우셔도 됩니다. 참고하세요.

2021-02-23 12:19 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Coffee.swift
> +    var price: Int
내부 속성은 private var로 지정하거나 필요하면 private(set) 정도로 지정하세요.
public var는 절대로 선언하는 것은 절대 안됩니다.

2021-02-23 12:19 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Drinks.swift
> +    private var dinks: [Drinkable]
이런 시도는 매우 좋습니다 :) 
다만 상위 클래스가 있는 경우는 프로토콜을 따로 정의할 것인가, 상위 클래스를 사용할 것인가 고민해볼 필요는 있습니다.

2021-02-23 12:19 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Milk.swift
> +    var price: Int
하위 클래스에서 상위 클래스에 선언한 속성을 동일하게 똑같이 선언할 필요는 없습니다.

2021-02-23 12:19 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Utility.swift
> +    }
- Utility는 어떤 경우에 선언하는 건가요?
- 이 메소드는 어떤 타입과 관련이 높을까요?

2021-02-23 12:19 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachine.swift
> +        drinks.retrieveDrinks(completion: completion)
이렇게 하니까 매우 깔끔하네요.

2021-02-23 14:55 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Utility.swift
> +    }
Date 타입과 관련 있어 Date 타입에 extension 하도록 변경했습니다!

2021-02-23 15:23 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Coffee.swift
> +    var price: Int
접근 제어자 수준을 private 또는 private(set) 수준으로 변경하였습니다.😉

2021-02-24 01:08 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Drink.swift
> +    private var price: Int
private var가 부담스러우면 private(set) 또는 let 도 가능한지 고려해보세요. 
값을 가져가는냐... 바꿀 수 있느냐 모두 고려해야 하긴 합니다.

2021-02-24 01:08 UTC, merged