[Downey]Step 2 - DownCasting, Set, Access Control
code-squad/swift-vendingmachineapp pull request #241
Opened 2021-02-25 12:53 UTC by dahun-lee-daji

# 작업 목록 
## 음료 클래스
- [x] 음료 클래스 3단계 이상 구현
- [x] 상위 클래스에 없는 하나 이상의 속성
- [x] 속성에 대한 추가 인터페이스
- [x] 추가 인터페이스
- [x] testCode

## 자판기
- [x] 원하는 금액만큼 올리는 메소드
- [x] 재고 추가 메소드
- [x] 구매가능 목록 리턴 메소드
- [x] 음료수 구매 메소드
- [x] 잔액 확인 메소드
- [x] Dictionary Type 재고 return method
- [x] 유통기한 지난 재고 return method
- [x] 따뜻한 음료 return method
- [x] 구매 이력 return method
- [x] testCode 

# 학습 키워드
DownCasting, Set, Access Control

# 고민과 해결
## Access Control
이전에, 상위 모듈에서 하위 모듈의 property에 접근하면 안된다는 가르침이 있기에, 이를 따르기 위해 class의 property를 private으로 선언하여 사용했습니다. 하지만 상위 모듈에서 Drink.name이 필요한 경우가 다수 발생하여 고민하여 여러 방안을 생각 했습니다.
1. private (set) var name
2. getName() -> String
3. super.description.componets ~~~~~~ 
4. closure

 위와 같은 방법 중 2,3 은 옳지 않은 방법이며, 4로는 super.name에 접근할 수 없었기에 1을 택했고, 질문에 대한 답변으로도 긍정정인 면이 있었기에 1 의 방법을 택했습니다.

## Set
isHot()과 같은 method에서 반환 값을 Dictionary<Drink,Int> 로 구현했을때 각 Drink마다 manufacturing이 상이하므로, 중복된 상품의 이름이 나왔습니다. 이를 해결하기 위해, 반환값을 Set<Drink.name, Int>로 변경했습니다.

## DownCasting
isHot()과 같은 method의 경우 매개변수로 Drink로 받는데, 하위 class중 isHot이 없는 method를 구분해야 했습니다. protocol Hotable을 만들어 매개변수로 protocol을 지정하는 것도 생각해봤지만, class 내부 property의 Access Control이 불가하므로, 이를 제외하였습니다. 이 외의 방법으로 DownCasting을 생각해내어 적용했습니다.

2021-02-26 05:30 UTC, godrm requested changes
수고하셨습니다. 다음 피드백 내용을 확인해서 개선해보세요.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/ChocoMilk.swift
> +//http://emart.ssg.com/item/itemView.ssg?itemId=0000007095603&siteNo=6001&salestrNo=2034
이건 그냥 본인이 참고한 쇼핑 아이템이니까 소스에 포함할 필요는 없지 않을까요?
소스 코드를 이해하는 데 꼭 필요한 정보일까요?

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/ChocoMilk.swift
> +    private let realChocolate : Bool //how many day after manufacturingDate
두 가지 측면이 있습니다.
- 주석과 코드가 불일치합니다. 이런 주석은 정말 혼란을 줄 수 있습니다. 없는게 낫죠
- realChocolate 함유가 된건지 여부만 Bool로 지정할 수도 있지만, 이런 경우는 함유량을 모델링하고 일정 기준이 넘어가면 true/false로 주는 메소드를 제공하는 게 더 좋은 방법입니다. 속성을 선언할 때도 고려해보세요.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Coffee.swift
> +    private let caffeine : Double?
정보를 표현하는 주석이 구체적이지 않고 혼란을 줄 수 있으면 차라리 없는게 낫습니다. 참고하세요.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Coffee.swift
> +        return "\(nonOptional) mg"
데이터를 Double로 갖고 있는데 판단해주는 것이 String인 것은 적합하지 않습니다. 
용량을 가져가서 그걸로 판단해서 어떻게 출력할 지는 뷰와 관련이 높습니다. 데이터를 보관하는 객체가 판단할 필요는 없습니다.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Cola.swift
> +    }
이런 경우도 데이터 선언과 메소드를 분리해서 Bool 타입으로 저장하지 않고 당분 함유량 같은 값을 보관하는 형태가 좋습니다.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    }
hash(into:)와 hashValue 차이점은 뭔가요? 꼭 둘 다 선언해야 하던가요?

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +        return Date.init(timeInterval: TimeInterval(days * 3600 * 24), since: manufacturing)
이 메소드는 음료 속성과 관련이 없어보이네요?
만약 기준 제조일부터 며칠 지난건지 판단하려는 거라면 Date와 관련이 있지 않을까요?

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    }
이 메소드도 내부 속성을 안 쓰는것 같은데요? 어떤 타입과 관련이 있는걸까요?

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drinks.swift
> +            throw errorCase.outOfIndex
에러를 잘 정의하셨네요. 이런 경우 그냥 옵셔널 정도로 처리할 지 throw 할 지 결정이 중요합니다.
에러는 옵셔널로 의미를 표현하기 어렵거나 2가지 이상 다양한 경우에, 그리고 정상적으로 처리하기 어려운 심각한 상황에서 쓰도록 권장하는 편입니다. 이정도는 옵셔널도 안전하게 처리할 수 있을 것 같습니다.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drinks.swift
> +        closure(drinks)
클로저를 넘기는 방법도 다양한 방법을 시도해보세요. 
처음에는 이렇게 다 넘기는 것도 가능하지만
조건에 따라서 해당 음료수만 골라서 넘기는 메소드를 따로 구현하는 것도 좋습니다.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Milk.swift
> +    private let expirationLimit : Int //how many day after manufacturingDate
날짜/기간과 관련된 것은 Int 보다는 Date 혹은 TimeInterval 같은 타입도 고려해보세요.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Milk.swift
> +    func validate() -> Bool {
validate 라는 함수를 주석을 설명해주는 시도는 좋습니다.
다만 함수 이름으로 그것을 더 잘 표현하는 게 주석 보다 좋습니다. 
validate가 구체적으로 뭘한다는 것을 알 수 없는데, 위에 주석보다 명확한 함수 이름이라면 주석을 뺄 수 있을 것 같습니다.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Soda.swift
> +    private let package : Materials
Materials 타입을 Soda에서만 쓰는 거라면 여기 근처에... 아니면 다른 파일에 있어도 될 것 같습니다.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/StrawberryMilk.swift
> +    private let cochineal : Bool //how many day after manufacturingDate
이 속성도 정보가 주석과 불일치하네요.
색소 정보인가요?

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/TOP.swift
> +    private let hot : Bool
뜨겁다는 정보도 Bool 보다는 온도를 저장하고 기준 온도보다 낮냐 높냐를 판단해주는 메소드가 있는게 좋습니다.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +    private var money : Int
money도 타입으로 선언해보면 어떨까요?

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            })
이렇게 두 단계로 클로저를 두는 것은 그냥 배열을 가져온 것과 사실 다르지 않습니다. 
클로저를 사용할 때도 구체적인 동작을 고려해보세요.

2021-02-26 05:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            })
모든 것을 하나의 클로저로 처리해야 하는 건 아닙니다.

2021-02-26 05:31 UTC, dahun-lee-daji commented on VendingMachineApp/VendingMachineApp/Model/ChocoMilk.swift
> +//http://emart.ssg.com/item/itemView.ssg?itemId=0000007095603&siteNo=6001&salestrNo=2034
불필요한 정보입니다. 추후 제가 해당 상품 내용을 보려고 적어놓은 내용입니다ㅎㅎ; 삭제하고 진행하겠습니다!

2021-03-02 10:26 UTC, dahun-lee-daji commented on VendingMachineApp/VendingMachineApp/Model/Milk.swift
> +    private let expirationLimit : Int //how many day after manufacturingDate
해당 property를 추가 할 때, "몇 일"을 모델링 하려고 했습니다.
실제 method 구현 시에도, 3일 뒤라고 했을 때, 이를 매개변수로 제공하여 TimeInterval : expirationLimit * 3600 * 24 를 이용하거나 Calendar를 사용할 때에도 Int 가 더 유리하다고 생각했습니다.

expirationLimit을 Date로 사용 할 경우, 몇 일 뒤를 init 할 경우, 3일 뒤를 표현하기 어려울 것이라 생각했으며,
TimeInterval을 사용 할 경우, second를 init의 매개변수로 제공해야 하는데, 이는 사람이 보기 쉽지 않으며 Data를 가공하기 어려울 것이라 생각했습니다.

2021-03-02 10:30 UTC, dahun-lee-daji commented on VendingMachineApp/VendingMachineApp/Model/Drinks.swift
> +            throw errorCase.outOfIndex
Drinks.remove()는 매개변수 productType과 같은 타입을 찾아서 pop합니다.
때문에, firstIndex를 찾지 못했을 경우, 옵셔널 처리를 할 경우, drinks.remove가 틀린 동작을 할 수 있다고 여겨, throw 했습니다.

2021-03-02 10:35 UTC, dahun-lee-daji commented on VendingMachineApp/VendingMachineApp/Model/Soda.swift
> +    private let package : Materials
넵 그래서 enum/Materials파일에 있습니다!

2021-03-02 10:35 UTC, dahun-lee-daji commented on VendingMachineApp/VendingMachineApp/Model/StrawberryMilk.swift
> +    private let cochineal : Bool //how many day after manufacturingDate
주석 제거하였습니다.
해당 내용은 색소 정보가 맞습니다!

2021-03-02 11:19 UTC, dahun-lee-daji commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            })
closure에 대한 피드백이 이해가 조금 어렵습니다 ㅜ
doClosure()를 반복적으로 사용하지 말라는 말씀이신가요?  -> doClosure()외에 특정 음료에 대한 closure method를 추가를 말씀하시는 걸까요?

2021-03-02 11:22 UTC, dahun-lee-daji commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            })
배열을 그냥 가져온 것 과 다르지 않다는 건 .forEach()를 말씀하신 건가요?
구체적인 동작을 고려해보라는 말씀이 어떤 것인지 잘 모르겠습니다..ㅠㅠ

2021-03-02 11:34 UTC, dahun-lee-daji commented
1차 수정 내용 : 
불필요, 틀린 내용의 주석 제거.
Coffee.productCaffeine() -> String에서 Double로 수정.
TOP의 hot : Bool, ChocoMilk의 realChocolate: Bool, Cola의 unsweetened: Bool 을 구체적 수치로 변경, 및 관련 메소드 수정
유통기한 확인 method = validate() 메소드 명 변경
Drink 내부의 Date관련 method 로직 및 매개변수 수정하여 Date.Extension으로 이동.
money : Int 에서 SafeBox로 변경.

Hashable프로토콜 채택 내용 수정 : `var hashValue: Int {}` 내용 삭제.
-> swift5에서 변경된 내용. Hasher가 hashValue를 생성해주기 때문에, func hash 내에서 hasher.combine method를 사용하여 essential parts를 mixing해주기만 하면 됨.

반영되지 않은 피드백 : closer method 관련 내용
-> 피드백 내용의 이해가 어렵습니다 ㅜㅜ
closure에 대한 피드백이 이해가 조금 어렵습니다 ㅜ

doClosure()를 반복적으로 사용하지 말라는 말씀이신가요? -> doClosure()외에 특정 음료에 대한 closure method를 추가를 말씀하시는 걸까요?

Dictionary를 만들어 재고를 보여주는 method에서 배열을 가져온 것과 다름없다고 말씀하신 것과, 구체적인 동작을 고려해보라는 말씀이 이해가 잘 되지않습니다.
drink.name을 key로 하여, Dictionary내에 해당 key에 대한 value 가 없을 경우, 값을 넣어주며, 있을경우 value += 1  하는 동작입니다. 
-> drinks.forEach를 사용한다면 배열을 가져온 것과 같은 내용인가요?, 제 생각에는 구체적인 동작을 하고 있는 것 같은데, JK의 의도가 뭔지 파악이 어렵습니다 ㅜㅜ

2021-03-02 13:57 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Milk.swift
> +    private let expirationLimit : Int //how many day after manufacturingDate
그렇지 않습니다. Date 생성자나 메소드 중에도 3일뒤를 계산할 수 있는 메소드가 있습니다.
더구나 3일뒤 라는 것을 직접 계산하는 게 절대 수월하지 않습니다. 섬머타임이 있다거나 타임존이 바뀌거나, 비행기에서 날짜가 바뀌는 경우는 더 계산이 복잡해집니다. Date는 그런 것을 모두 고려해서 구현되어 있는 타입니다.

2021-03-02 13:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            })
모든 것을 클로저로 구현하지 말라는 거죠. 
클로저가 아니라 정해진 형식대로 메소드를 호출하고 return 값을 전달해도 되는 것을 모두다 클로저로 구현할 필요는 없습니다.

2021-03-02 13:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/ChocoMilk.swift
> +        return chocolateContent > 20
여기서 기준값 20을 상수로 선언하거나 사위 타입으로 선언하고, 매개변수로 전달하는 구조도 좋습니다.

2021-03-02 13:59 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/ChocoMilk.swift
> +    private let chocolateContent : Double // percent
비율보다는 용량이 더 좋습니다. 비율은 생각보다 정확한 값이 아닙니다. 오차가 생길 수 있습니다.
내용물로 비율을 계산하는 게 더 정확합니다.

2021-03-02 14:00 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Cola.swift
> +    private let sugarContent : Double
Double 이나 Float를 사용할 때는 오차 범위나 표현범위를 고려해야 합니다. 참고하세요.

2021-03-02 14:01 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    private (set) var manufacturing: Date
값을 가져가기 보다는 메소드를 제공하려고 노력해보세요.

2021-03-02 14:03 UTC, godrm commented on VendingMachineApp/VendingMachineApp/extention/Date.swift
> +        return Date.init(timeInterval: TimeInterval(days * 3600 * 24), since: self)
add() advance() 같은 메소드와 어떻게 다를까요?

2021-03-02 14:08 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            })
클로저를 활용하라는 측면은 값을 가져오지 않고 로직을 전달하기 위한 방법 중에 하나입니다.
더구나 내부 속성이 2차원 배열인데 doClosure와 drinks.forEach로 2차원 배열을 그대로 탐색하는 방법은 drinks 라는 내부 배열을 그대로 가져간 것과 별로 다르지 않다는거죠. 
클로저를 활용하지 않고 이런 메소드가 `stock.show() -> Dictionary<String,Int>`있는 것보다 오히려 더 안좋다는 의미입니다. 모든 메소드를 클로저를 넘기는 방식으로 구현하지 않아도 됩니다. 
클로저로 내부에서 구현해도 될 것 까지 통째로 클로저로 제공하라는 게 아닙니다.

2021-03-02 14:10 UTC, godrm commented
고민이 드러나는 것 같습니다. 다만 제가 더 구체적으로 이렇게 바꾸세요. 라고 하지 않는 것은 힌트정도로 답을 찾아가길 바래서입니다.
제가 의도한 데로 고치는 게 중요한 게 아니라 스스로 무엇을 고쳐야 할 지 깨닫는 게 더 중요합니다. 
제 피드백에 맞춰서 그걸 해결하려고 하지마시고, 이해가 안되면 더 질문을 댓글로 남기세요. 고민하다가 수정하지 못하는 것보다 질문하는 게 더 좋습니다. 리뷰는 저의 의견에 맞춰서 일방적으로 구현하자는 게 아닙니다. 코드로 저를 설득하려고 하셔야 합니다.

2021-03-02 14:10 UTC, merged

2021-03-03 05:17 UTC, dahun-lee-daji commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            })
아 제가 클로저로 넘기는 거에 너무 꽂혀있던 것 같습니다.
답변 감사합니다!