[Soo] Step2 - 3단계로 음료 객체 정의, 자판기 기능을 위한 함수 추가
code-squad/swift-vendingmachineapp pull request #247
Opened 2021-02-26 03:17 UTC by lenaios

[주요 작업]
- [x] 3단계로 음료 객체 정의
- [x] 자판기 기능을 위한 함수 작성
- [x] 단위 테스트를 위한 테스트 코드 작성

[학습 키워드]
- Hashable, XCTest

[고민과 해결]
- `validate` func을 이용해 유통기한이 지난 상품을 검색할 때, 입력 받은 date보다 제조 일자가 이후일 경우로 체크하였습니다. 하위 객체마다 expiry date 속성을 정의해줘야 하는지 고민했는데, 속성을 추가하게 되면 init도 수정해야 해서 비용이 적은 편을 선택했는데 올바른 선택인지 궁금합니다🤔..!

2021-02-26 06:25 UTC, godrm requested changes
요구사항에 있는 기능이 빠진 게 있는 것 같습니다. 확인해봐주세요.

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/BananaMilk.swift
> +    private let isUnsweetened: Bool
이런 경우는 함유량을 넣고 필요한 경우는 Bool 보다는 범위가 있는 타입으로 하고 비교하는 메소드를 제공하는 게 좋습니다.

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Cantata.swift
> +    private let isHot: Bool
hot 같은 상태는 Bool 타입보다 온도를 속성으로 놓고 그 온도보다 높냐 낮냐 같은 메소드를 제공하는 게 좋습니다.  
데이터를 모델링할 때 Bool 타입은 조심해서 선언하세요. 정말 딱 2가지 경우만 있는게 좋습니다.

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +    }
validate가 지난 것을 의미하는지, 이전 것을 의미하는지 불명확한 것 같습니다. 
좀 더 명확한 단어로 표현하면 좋겠습니다.

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +    private(set) var dateOfManufacture: Date
이 속성은 왜 private(set)일까요? 값을 가져가서 비교하는 거라면 비교하는 메소드를 제공하는 건 어떨까요? 
이름에 Date 타입을 포함하지 않고 manufacturedAt 정도로 표현하기도 합니다. 참고하세요

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +}
Hashable 프토콜은 어떤 경우에 써야 하나요? HashValue 와는 어떻게 다른가요?

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Fanta.swift
> +    private let packageMaterial: PackageMaterial
지금은 enum 타입으로 속성을 지정해도 무난합니다만 확장, 변화가 많은 타입은 enum 타입보다는 하위 클래스로 선언하는 게 더 좋습니다. 참고하세요.

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Milk.swift
> +    private let expriryDate: Date
expriryDate가 특정한 유통기한 날짜를 나타내는 거겠죠? 혹시 제조일자로부터 유통기간을 나타내는 것일까요? 
둘 중에 어떤 것인지 명확하게 표현할 수 있으면 좋겠습니다.

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Soda.swift
> +    private let calorie: Int
어떤 속성이 있으면 이 속성으로 무언가 판단하는 메소드가 있는지도 잘 생각해보세요.
그렇지 않으면 아무 쓸모없는 값을 보관하는 거죠.

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/VendingMachine.swift
> +    private var purchaseHistory = [Drink]()
purchaseHistory도 별도 타입으로 구현하면 어떨까요?

2021-02-26 06:25 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/VendingMachine.swift
> +    }
뭔가 요구사항에 있는 자판기 기능이 빠진 것 같은데요? 모두 구현한 게 맞나요?

2021-03-02 06:29 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/BananaMilk.swift
> +    private let isUnsweetened: Bool
fatContent, sugarContent와 같은 속성을 정의해서 범위가 있는 Int 타입으로 주고, isLowFat(), isUnSweetened() 함수로 기준치 미만/초과에 대한 Bool값을 리턴하도록 개선해보았습니다.😊

2021-03-02 06:30 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/Cantata.swift
> +    private let isHot: Bool
이 경우에도 음료에 temperature 속성을 추가해서, 파라미터로 받은 온도와 비교해 따뜻한 음료인지 아닌지 결과를 리턴하는 메소드를 추가하였습니다.

2021-03-02 06:30 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +    }
validateExpiredAt로 함수명을 변경하고, 유통기한 지남 여부를 체크하도록 수정하였습니다.

2021-03-02 06:30 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +    private(set) var dateOfManufacture: Date
속성 값을 그대로 가져다 쓰지 않고, validateExpiredAt와 같이 비교하는 메서드를 추가하였습니다.

2021-03-02 06:30 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/Fanta.swift
> +    private let packageMaterial: PackageMaterial
넵 참고하겠습니다!😉

2021-03-02 06:30 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/Milk.swift
> +    private let expriryDate: Date
특정 유통기한 날짜를 의미하도록 expiredAt 으로 네이밍을 변경하였습니다.😊

2021-03-02 06:31 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/Soda.swift
> +    private let calorie: Int
하위 클래스가 가지고 있는 속성을 가지고, 어떤 기능을 하는 메서드를 최대한 추가해봤습니다. farmCode 같은 속성은 어떤 관련 있는 일을 해야 할지 잘 모르겠네요..ㅠㅠ

2021-03-02 06:31 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/VendingMachine.swift
> +    private var purchaseHistory = [Drink]()
피드백 반영하여 수정했습니다.😊

2021-03-02 06:31 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/VendingMachine.swift
> +    }
누락된 요구사항 추가했습니다.😅

2021-03-02 06:31 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +}
Dictionary의 Key는 Hashable 프로토콜을 준수한 타입이어야 하기 때문에, Hashable을 사용했습니다.
Hashable Protocol은 integer hash value를 제공할 수 있는 타입을 의미하며, 프로토콜을 준수하기 위해서 hash 메소드를 필수로 구현해야 합니다.
hashValue는 hasher에 의해 생성된 hash 값을 의미합니다.

2021-03-02 06:35 UTC, lenaios commented
리뷰 주신 내용을 바탕으로 수정해서 다시 push 했습니다.
하위 클래스의 속성과 기능을 정의하는 부분이(=설계?) 가장 고민됐던 것 같습니다.😥
확인 부탁드립니다!🙏 _ _

2021-03-02 06:54 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +        return gap > 0 ? false : true
두 가지 의견이 있습니다.
- 매개변수로 넘기는 타입도 하위 타입으로 지정하면 기준값을 지정하기 좋습니다.
- return 할 때 비교식이면 그냥 그대로 쓰세요. `return self.temperature - temperature > 0` 그게 더 읽기 좋습니다.

2021-03-02 06:57 UTC, godrm commented
수고하셨습니다.

2021-03-02 06:57 UTC, merged

2021-03-02 06:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Soda.swift
> +    private let calorie: Int
제한적인 미션이기는 해서 약간의 상상력이 필요하긴 합니다.

2021-03-02 07:00 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +}
사용하는 곳이 다르긴 합니다. 두 가지가 비교하는 값이 다르면 결과가 달라질 수 있겠죠. 
예를 들어 지금 상태로 Dictionary에 manufacturer는 같고, 브랜드가 다른 인스턴스를 넣으면 더 넣을 수 있을까요? 없을까요?

2021-03-02 14:28 UTC, lenaios commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +}
지금 상태 기준으로는 manufacturer가 같고, 브랜드가 다른 인스턴스는 Dictionary에 각각 다른 key로 들어갈 것 같은데...
== 을 사용하는 곳과 hashValue를 사용하는 곳이 다르다는 의미로 이해하면 될까요?🤔

2021-03-02 14:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Drink.swift
> +}
다른 점을 이해하고, 속성값을 비교할 때 기준값을 잘 정해야 한다는 겁니다. 
hash(into:) 로 비교하는 곳에서는 manufacturer만 비교하니까 다른 값과 구분이 안되는 경우가 생기겠네요.