[Min] Step2 자판기 구조체 생성 및 메소드 구현 & Unit Test Code 구현
code-squad/swift-vendingmachineapp pull request #251
Opened 2021-02-27 10:28 UTC by youngminshim-de

- [ ]  클래스 모델 객체들의 계층에 따른 파일분리
- [ ]  Enum Type으로 세부클래스(3단계) type 지정 -> Enum Type 제거 후 각 각의 세부클래스에서 type 지정하도록 수정
- [ ] VendingMachine Struct 구현
- [ ] [Beverage] 배열을 다루기 위한 Inventory Class 구현
- [ ] Unit Test Code 작성

## 고민과 해결

- Hashable

    전체상품의 재고를 종류별로 리턴하는 메소드를 구현하면서, Dictionary를 사용하여 구현하려했으나 Dictionary의 key 값은 Hashable 해야한다는 것을 처음에 몰라, Hashable에 대해 공부하고, Beverage Type을 사용하기 위해 Hashable을 채택했습니다.

- Enum Type

    Step1 에서 세부 클래스의 각 각의 Type을 Enum 으로 제한해주는 방식으로 구현했었는데, Step2 에서는 Enum Type을 지우고 각 각의 세부 클래스 내부에서 초기화 해주는 방식을 채택했습니다. 매개변수로 넘겨주지 않고 내부에서 type을 직접 지정해줌으로써, Type을 제한해주는 것과 같은 효과를 주려고 했는데, 이렇게 해도 되는건지는 사실 정확히 판단이 서지는 않습니다..

- Inventory Class

    VendingMachine 구조체에서 배열을 직접 다루지 않기 위해 Inventory Class를 구현하여 배열과 관련된 모든작업을 수행하도록 구현했습니다.

    VendingMachine 에서는 Inventory 의 메소드만 호출하고, 실질적인 모든 처리는 Inventory에서 진행하는데, 이 과정에서 method 명이 많이 중복되는데, 이처럼 작성해도 되는것인지 궁금합니다..

2021-03-01 11:48 UTC, godrm requested changes
수고하셨습니다. 
-3단계 계층 속성과 Inventory 부분은 꼭 수정해보세요.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/BananaMilk.swift
> +    private var type: String
type 이라는 것이 구체적이지 않네요. 세부 타입을 지정하거나 속성 이름을 더 구체적으로 정하는 게 좋습니다.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage.swift
> +    private var expirydate: Date
expirydate에 타입Date 이름을 붙이지 않는 게 좋습니다. 명확하게 그 역할을 표기하는 습관을 가지세요.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage.swift
> +    private var hot: Bool
뜨겁다/차갑다 같은 상태는 온도를 모델링해서 표현하고, isHot()을 메소드로 제공하는 게 좋습니다. 
Bool 타입은 명확하게 2가지로 나눠지는 경우에만 사용하세요.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage.swift
> +        return calorie <= compareCalorie
이런 경우는 기준값을 상수로 지정하더라도 매개변수로 넘겨줄 수 있도록 작성하는 게 유연한 방식입니다.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage.swift
> +    func validate(with date: Date) -> Bool {
validate(with: Date)는 날짜가 지난것을 판별하는지, 이전것을 판별하는지 구체적이지 않습니다.
동작을 좀 더 명확하게 설명하는 표현을 지정해주세요.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage.swift
>      }
hash와 hashValue는 어떤 차이가 있나요? Equatable == 연산자만 구현하면 안되던가요?

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Cantata.swift
> +    private var type: String
세부 속성은 이전 수퍼 클래스와 하위 클래스를 구분해주는 명확한 기준이 됩니다.
커피와 칸타타를 구분해주는 정보여야 합니다.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/ChocoMilk.swift
> +    private var type: String
이렇게 선언한 모든 타입들이 다 같은 type이라는 속성으로 지정하는 것이 아니라 세부적인 속성을 선언해야 합니다.
그렇지 않으면 수퍼 클래스와 구분이 안되서 그냥 상위 타입을 써도 됩니다.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Date.swift
>          return Date.dateFormatter.date(from: date) ?? Date()
이렇게 인스턴스를 생성하는 것은 팩토리 메소드라고 합니다.
함수 이름도 비교적 규칙적으로 만들어서 명확하게 선언하는 편입니다. 참고하세요.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +    private var purchaseHistory: [Beverage] = []
인벤토리 클래스 역할은 무엇인가요? 구매 이력까지 모두 보관하는 것까지 인가요?
자판기와 역할 분담이 어떻게 되는걸까요?

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +        })
내부 메소드들까지 꼭 클로저형태로 접근해야 하는 건 아닙니다. 그냥 inventory.forEach{} 하는 것과 다르지 않을것 같은데요?

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Milk.swift
> +    private var lowFat: Bool
isHot 처럼 속성에서 lowFat을 Bool 타입으로 선언하기 보다는
모델에서는 값을 범위로 갖고 있고, 기준값보다 낮으면 lowFat 이라고 판단하는 메소드를 제공하는 게 좋습니다.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Soda.swift
> +    private var flavor: String
여기까지 읽어보니 2단계 계층까지는 속성이 있는데 3단계 계층은 세부 속성이 불명확하네요.

2021-03-01 11:48 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/VendingMachine.swift
> +    private var money: Int
Money도 하위 타입으로 선언해보세요.
Inventory가 하위 타입으로 꽤 많은 것을 가져갔는데, 정말 인벤토리랑 관련있는 것들만 처리하고 있을까요?

2021-03-02 06:56 UTC, youngminshim-de commented on VendingMachineapp/VendingMachineapp/Model/VendingMachine.swift
> +    private var money: Int
상위 모듈인 VedingMachine에서 직접적인 Data의 처리가 일어나면 안되서 하위 타입으로 선언해야 하는건가요?
사실 정확히 왜 그렇게 해야하는지 잘 판단이 서질 않습니다.
배열과 같은 처리들을 하위모듈(Inventory)에서 처리하라는 것과 같은 맥락이겠지요?

2021-03-02 08:46 UTC, youngminshim-de commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +    private var purchaseHistory: [Beverage] = []
재고를 추가하고 빼는 메소드를 제외하고는 VendingMachineManager 클래스를 만들어 분리했습니다.
VendingMachine < VendingMachineManger < Inventory 이런식으로 구현하다가 또 너무 많은 중복되는 함수가 생겨
VendingMachine 에서 manager 와 inventoryf를 모두 가지고 있는 형식으로 구현했습니다.

2021-03-02 08:47 UTC, youngminshim-de commented on VendingMachineapp/VendingMachineapp/Model/Soda.swift
> +    private var flavor: String
속성들을 추가하는데도 많은 시간이 걸리네요.. 약간 억지로 넣은 느낌이 많이 나지만 각 각 하위 계층에 세부속성을 추가했습니다

2021-03-02 08:53 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Soda.swift
> +    private var flavor: String
네. 지금 하는 게 약간 억지로 구분하고 있기는 합니다.

2021-03-02 08:55 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/VendingMachine.swift
> +    private var money: Int
네. 같은 맥락이구요. 하위 타입을 만들어서 동작을 분리하는 연습을 하는거죠. 
어떤 개념이 있으면 그 개념을 담당하고, 속성과 메소드를 포함하는 타입으로 선언하도록 반복해서 연습하는 겁니다. 
Int는 큰 의미에서 정수값이고, 우리는 정수값을 다루는 게 아니라 Money라는 역할과 책임을 다루려는 겁니다.

2021-03-02 08:56 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +    private var purchaseHistory: [Beverage] = []
인벤토리와 구매 이력은 서로 다른 개념 혹은 역할인 것 같은데 억지로 합쳐놓은 것 같아서요. 
하위 타입으로 만들더라도 덩어리를 어떻게 나누느냐 중요한 포인트가 될 수 있습니다.

2021-03-02 09:56 UTC, youngminshim-de commented
1. 변수명 변경 (변수명에 type이름 삭제) & 메서드명 & 매개변수 변경
2. inventory Class의 역할 분리 재고와 관련없는 역할들은 Vending Machine Manager Class를 만들어 메서드 분리
3. 팩토리 메소드 이용하여 Beverage(Coffee, Soda, Milk) Factory 구현

궁금점: 
1. enum Type 으로 3단계 클래스의 type을 정해놓는게 확장성이 좋지 않을것 같다는 지난 피드백을 받고 enum Type을 없앴습니다.
   그렇게 되면 Factory Method 에서 인스턴스를 생성해줄 때 default의 경우를 어떻게 처리하면 좋을지.. 잘 모르겠습니다.

2. init의 매개변수가 지금 많은데, 이러한 형식이 맞는건지 ? 만약 바뀌지 않는다고 판단이 된다면 매개변수 형식으로 받는게 아니라 직접 init()내부에서 설정하면 좋을지 궁금합니다.

2021-03-02 10:03 UTC, godrm commented
> 1. enum Type 으로 3단계 클래스의 type을 정해놓는게 확장성이 좋지 않을것 같다는 지난 피드백을 받고 enum Type을 없앴습니다.
>    그렇게 되면 Factory Method 에서 인스턴스를 생성해줄 때 default의 경우를 어떻게 처리하면 좋을지.. 잘 모르겠습니다.

기본값으로 사용하는 enum 정도는 선언해도 됩니다만. 세부 타입을 선언해야 할 경우까지 enum으로 지정하지만 않으면 됩니다.

> 2. init의 매개변수가 지금 많은데, 이러한 형식이 맞는건지 ? 만약 바뀌지 않는다고 판단이 된다면 매개변수 형식으로 받는게 아니라 직접 init()내부에서 설정하면 좋을지 궁금합니다.

init 매개변수는 많아질 수 밖에 없어요. 그래도 외부에서 입력을 받는 지정 생성자를 두고, 일부 값들은 간편 생성자로 같이 제공하는 게 좋습니다.

2021-03-02 10:09 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage/Coffee/CoffeeFactory.swift
> +        case "TOP아메리카노" :
이런 경우도 그냥 타입을 사용할 수 있는 방법이 있긴 합니다.
메타 클래스라는 클래스 타입 정보를 확인하는 방법을 찾아보세요.
Coffee.self 형태로 타입을 값으로 사용할 수 있습니다.

2021-03-02 10:09 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage/Milk/ChocoMilk.swift
> +    private var chocoContent: Int
이런 속성을 포함한다면 어떤 관련된 메소드가 있는게 좋은지도 고민해보세요.
억지로 속성만 추가하면 수동적인 타입으로 남게 됩니다.

2021-03-02 10:10 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage/Soda/Soda.swift
> +                   expiryTime: expiryTime,
expireTime 도 Date 타입인데 Time 이 붙어서 시각처럼 읽게 되네요. 
Date, Time 이런거 붙이지 말고 그대로 표현하셔도 됩니다.

2021-03-02 10:11 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/VendingMachine.swift
> +        return money.checkChange()
Money를 타입으로 선언했으면 그냥 return 도 Money로 해도 됩니다.

2021-03-02 10:12 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/VendingMachineManager.swift
> +    }
이 메소드는 전형적으로 응집도가 낮은 메소드입니다.
왜냐하면 VendingMachineManager 속성과 전혀 상관이 없이 동작하기 때문입니다.
이 메소드는 Inventory와 더 관련이 높다는 의미가 됩니다.

2021-03-02 10:12 UTC, godrm commented
수고하셨습니다. 다음 단계를 진행하면서 개선해보세요.

2021-03-02 10:12 UTC, merged