[Elly] Step2 - 음료수 3계층 설계, XCTest, Factory pattern
code-squad/swift-vendingmachineapp pull request #252
Opened 2021-02-27 13:51 UTC by ellyheetov

##  프로그래밍 요구사항
 - [x]  자판기 금액을 원하는 금액만큼 올리는 메소드
 - [x]  특정 상품 인스턴스를 넘겨서 재고를 추가하는 메소드
 - [x]  현재 금액으로 구매가능한 음료수 목록을 리턴하는 메소드
 - [x]  음료수를 구매하는 메소드
 - [x]  잔액을 확인하는 메소드
 - [x]  전체 상품 재고를 (사전으로 표현하는) 종류별로 리턴하는 메소드
 - [x]  유통기한이 지난 재고만 리턴하는 메소드
 - [x]  따뜻한 음료만 리턴하는 메소드
 - [x]  시작이후 구매 상품 이력을 배열로 리턴하는 메소드
 - [x]  각 메소드 동작을 검증할 수 있는 테스트 함수를 작성한다.
 - [x]  전체 코드를 확인할 수 있는 통합 테스트 시나리오를 가지고 동작을 확인한다.

## 학습 키워드
- Factory Pattern
- Hashable, Equatable

## 고민 한 것 & 개선하고 싶은 부분
- 단위 테스트를 하려고 최대한 시도하였습니다. 하지만, 객체를 생성하는 부분에 있어서 단위 테스트가 잘 이루어지지 않고 있는 것 같습니다.
- 팩토리 패턴을 적용하려고 시도하였습니다. 하지만, 잘 이해하고 설계한건지 판단이 서지 않습니다. 더 공부해야 할 것 같습니다...ㅎ
- create, expire 변수를 어떻게 초기화 해야할지 어려웠습니다. 같은 제품에도 생성일자와 유통기한은 다르기에, default 생성자를 넣지 않으려고 하였습니다. 매번 상수로 초기화 해야하는 불편함이 존재하여, 임시로 생성시점의 시간으로 초기화 하였습니다.
- 하위 객체로 갈 수록 데이터를 추가해야 하는데, 어떤 데이터를 추가해야할지 정말 고민을 많이 했습니다.
- Protocol을 최대한 사용하려고 했지만, 아직 덜 적용이 된것 같습니다.

2021-03-01 12:05 UTC, godrm requested changes
수고하셨습니다 .다음 피드백을 확인해보시고 개선해보세요.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Beverage.swift
> +    private let expire : Date
이런 경우는 동사 원형보다는 createdAt, expiredAt 처럼 과거형을 많이 쓰는 것 같습니다.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Beverage.swift
> +        return price <= coins
이 함수도 가격이 가능하냐? 물어보는 것과 더 명확하게 가격이 더 낮아? 라고 표현하는 게 어떨까요?

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Beverage.swift
> +        return calendar.compare(Date(), to: expire, toGranularity: .day) == .orderedAscending
두 가지 측면이 있습니다. 
- 이런 메소드를 만들 때 isExpired() 처럼 부정적인 것을 선언할 것이냐 아니면 유통가능한 것인지 긍정적으로 판단할 것인지 고민해보세요. 부정적이면 리턴타입이 true 일 때 부정인지, 긍정인지 헷갈릴 수 있습니다.
- 날짜 비교는 당연히 필요합니다만, 구현 자체는 여기다 할 것인가. 아니면 특정일 기준으로 지난 것인지 판단하는 함수를 구현해놓고 호출할 것인지 비교해보세요.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Beverage.swift
> +    }
Equatable 을 구현했으면 compare 보다 더 정확하지 않나요? 이름만 비교하는 게 필요했던 걸까요?

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Coffee/Cantata.swift
> +class Cantata : Coffee {
Coffee 타입보다 서브 클래스니까 더 세부적인 속성이 뭔가 있어야 합니다.
그렇지 않으면 그냥 Coffee 타입으로 대체가 가능하다는 의미가 됩니다.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Coffee/Coffee.swift
> +    private let hot : Bool
hot도 caffeine 처럼 온도를 값으로 보관하고 hot, cold 여부는 기준값보다 높은지, 낮은지 메소드로 제공하는 게 좋습니다.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Coffee/CoffeeFactory.swift
> +        let drink = Coffee.Kind(rawValue: name)
팩토리 메소드라면 name 문자열로 생성하기 보다는 타입 자체를 활용하는 게 좋습니다.
클래스 타입을 값으로 활용하려면 어떻게 해야할까요?
그런 것을 메타 타입이라고 합니다. 인스턴스 > 클래스 > 메타 클래스(타입) 관계가 성립합니다.
인스턴스가 같은 클래스인지 판단할 수 있고,  Int.self != String.self 메타 클래스끼리 비교도 가능합니다.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Consumer.swift
> +    private var purchaseList : [Beverage]
Consumer 라는 타입을 선언하는 것은 좋은 시도네요.
앞으로 다음 단계 요구사항에서도 고객과 관련된 변경이 이 클래스 내부에서만 일어난다면 구조적으로 잘 나눈 것이라고 판단하시면 됩니다.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Consumer.swift
> +    private(set) var coins : Int
coins 의 타입은 뭐가 좋을까요? 예를 들어 Money 타입을 선언할 수 있을까요?

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Consumer.swift
> +    }
여기 함수들은 띄어쓰기로 구분이 안되네요. 의도한 걸까요?

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/EnergyDrink/Monster.swift
> +
Hot6ix와 달리 Monster는 세부 속성이 없어서 EnergyDrink 타입으로 대체가 가능하네요.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Milk/ChocolateMilk.swift
> +    }
init()은 스위프트 문법에서 가장 규칙이 복잡한데요. 간결하게 만들려면 convenience init으로 만들어야 합니다.
무작정 줄이기보다는 규칙대로 만들어보고, default value를 지정해보세요.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/Milk/Milk.swift
> +
Milk도 세부 속성이 없네요.

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
> +    private var coins : Int = 0
Customer도 coins를 갖고 있던 것 같은데, 돈이 어디에 있는게 원천인가요?
데이터를 관리하는 객체가 어떤 객체가 더 소스인지 (하위 타입인지) 판단해보고 하나에서 관리하는 게 어떨까요?

2021-03-01 12:05 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
> +    private var stocks = Dictionary<Beverage,Int>()
stocks을 Dictionary<Beverage,Int>를 포함하는 하위 타입으로 선언해보면 어떨까요?

2021-03-01 13:30 UTC, ellyheetov commented on VendingMachineApp/Model/Coffee/Coffee.swift
> +    private let hot : Bool
보통 카페에서 혹은 자판기로 커피를 주문 시 핫인지 아이스인지만 선택하므로 온도를 지정하지 않았습니다.
혹시 구체적인 온도를 가지고 있을 필요가 있나요???

2021-03-01 13:42 UTC, ellyheetov commented on VendingMachineApp/Model/Consumer.swift
> +    }
- `buy` : 고객이 구매하기를 선택한 경우
- `put coins to vending machine` : 자판기에 돈을 넣는 경우
- `take balance` : 자판기에 남은 금액을 수거하는 경우
다음과 같은 상황을 고려하여 메소드들을 작성하였습니다. (다만, 언어적으로 맞는 표현은 아니네요😅)

2021-03-01 13:42 UTC, ellyheetov commented on VendingMachineApp/Model/EnergyDrink/Monster.swift
> +
세부 속성에 무엇을 넣어야 할지 몰라서 일단 남겨 두었습니다.

2021-03-02 00:54 UTC, godrm commented on VendingMachineApp/Model/EnergyDrink/Monster.swift
> +
약간 상상력을 발휘해보세요 :)

2021-03-02 14:16 UTC, ellyheetov commented
JK! 질문 있습니다🙋🏻‍♀️.

```swift
let str : String.Type = String.self
print(dict.first(where: {$0.key is str})) // Cannot find type 'str' in scope
```
dict라는 맵 자료구조에 있는 원소중 key가 String타입인 첫 번째 원소를 알아내고 싶은데,
해당 코드를 실행시키면 Cannot find type ‘str’ in scope 에러가 발생합니다.
str 변수가 왜 scope에서 벗어난 건지 잘 모르겠습니다.

2021-03-02 14:18 UTC, ellyheetov commented
Beverage > Coffee > Top 와 같은 클래스 구조를 가지고 있다고 할 때,
```
let dict = [Beverage:Int]

if dict[0].Type is Top.Type {
	// do something
}
```
혹시 이런 구조는 불가능 할까요???

구체적으로 다음과 같은 코드를 작성하고 싶습니다.

```swift
public func getProduct<T>(type item : T) -> Beverage?{ 
    let item = products.first(where: {$0.key is item.Type})
    return item.key
}
```
상품의 타입을 인자로 넘겨주면, 해당 타입에 적용되는 음료 인스턴스를 받아오고자 하는 함수입니다.

2021-03-02 14:27 UTC, godrm commented
> JK! 질문 있습니다🙋🏻‍♀️.
> 
> ```swift
> let str : String.Type = String.self
> print(dict.first(where: {$0.key is str})) // Cannot find type 'str' in scope
> ```
> 
> dict라는 맵 자료구조에 있는 원소중 key가 String타입인 첫 번째 원소를 알아내고 싶은데,
> 해당 코드를 실행시키면 Cannot find type ‘str’ in scope 에러가 발생합니다.
> str 변수가 왜 scope에서 벗어난 건지 잘 모르겠습니다.

str 타입과 값은 뭘까요? is 문법이 무엇을 기대할까요?

2021-03-02 14:28 UTC, godrm commented
@ellyheetov type(of:) 나 ObjectIdentifier 에 대해 찾아보세요 :)

2021-03-02 15:47 UTC, ellyheetov commented
<img width="380" alt="Screen Shot 2021-03-03 at 12 42 51 AM" src="https://user-images.githubusercontent.com/60229909/109673452-65156800-7bb9-11eb-93c4-608f06f35c37.png">

str의 값은 String이고 str의 type은 String.Type으로 확인 하였습니다.
`A is B`문법같은 경우 A가 B 프로토콜을 따르고 있는지를 확인하는 것으로 알고있습니다.
해당 결과를 보아도 감이 잘 오지 않네요.😅

2021-03-03 06:35 UTC, ellyheetov commented
```
class Stocks {
    milkStock : Stock
    SodaStock : Stock
    CoffeeStock : Stock
}
```
혹시 재고 관리를 다음과 같이 하는 것은 좋은 시도가 아닐까요???

물품의 종류와 상관없이 Beverage를 모두 담는 배열로 설계를 했으나, 원하는 타입의 음료수를 가져오기위해 탐색시 복잡도가 증가하는 것같아 분리하는건 어떨까 해서요.
다만 이렇게 분리하면, 물품의 종류가 늘어난다면 Stocks에서 관리하는 Stock이 하나 더 추가되어야 하는 단점이 존재하는 것 같습니다.

2021-03-03 07:41 UTC, godrm commented
> ```
> class Stocks {
>     milkStock : Stock
>     SodaStock : Stock
>     CoffeeStock : Stock
> }
> ```
> 
> 
> 혹시 재고 관리를 다음과 같이 하는 것은 좋은 시도가 아닐까요???
> 
> 
> 물품의 종류와 상관없이 Beverage를 모두 담는 배열로 설계를 했으나, 원하는 타입의 음료수를 가져오기위해 탐색시 복잡도가 증가하는 것같아 분리하는건 어떨까 해서요.
> 
> 다만 이렇게 분리하면, 물품의 종류가 늘어난다면 Stocks에서 관리하는 Stock이 하나 더 추가되어야 하는 단점이 존재하는 것 같습니다.

예상처럼 타입 자체를 활용하는게 더 좋습니다. 메타 클래스를 비교하기 어려우면 그냥 인스턴스로 구분하세요. 
다만 다형성을 활용하셔야 합니다. if-else 나 switch로 타입을 구분하면 안됩니다.

2021-03-03 08:06 UTC, ellyheetov commented on VendingMachineApp/Model/Consumer.swift
> +    private(set) var coins : Int
Money type을 추가하였습니다.

2021-03-03 08:37 UTC, godrm commented
수정이 완료되면 알려주세요. 커밋하면서 바로 push안하고 push는 한 번만 해도 됩니다.

2021-03-03 08:46 UTC, ellyheetov commented
# 수정 사항

1. Stock 객체는 내부에 Beverage를 관리하는 맵이 있었으나, 이를 배열로 변경하였습니다. Stock에 데이터를 넣고 빼는 과정과, 객체를 키 값으로 가지는 것이 부적절하다고 판단되었기 때문입니다. 

2. Beverage에 프로퍼티 명을 변경하였습니다 : create -> createdAt, expire -> expiredAt

3. Beverage에 compare함수를 제거하였습니다. 객체의 이름을 활용하여 인스턴스를 생성하는 부분을 객체의 타입을 이용하도록 변경하였으므로, 해당 함수가 필요 없어졌기 떄문입니다.

4. Date를 확장하여 인스턴스 메소드로 isExpired()를 선언하였습니다. 인스턴스의 값과, 현재 시간을 비교하여 유통기한이 지났을 경우 true를 반환합니다.

5. 하위 객체에 세부적인 속성을 추가하였습니다.

6. Convenience init을 적용하였습니다.

혹시 더 수정 사항이 있으면 수정 하도록 하겠습니다. 신랄한 리뷰 부탁드립니다.

2021-03-03 08:51 UTC, godrm commented
ㅎㅎ 이정도면 충분합니다. 다음 단계로 갑시다. 이제 뷰 붙여봐야죠.

2021-03-03 08:53 UTC, godrm commented on VendingMachineApp/Model/Coffee/Coffee.swift
> +    private let hot : Bool
ㅎㅎ 네. 그건 사용자가 결정하는 화면인거고 데이터 모델은 더 세부적인 값을 갖고 있도록 하는 게 좋다는 겁니다. 
내부는 복잡하지만 사용자는 간단하게 고르는거죠. 메뉴를 고르기 위한 거라면 그것도 좋습니다만 하위 데이터 타입을 모델링한다는 측면에서 고려해주세요.

2021-03-03 08:53 UTC, godrm commented on VendingMachineApp/Model/Stock.swift
> +*/
사용하지 않는 메소드는 과감하게 지우세요.

2021-03-03 08:54 UTC, godrm commented on VendingMachineApp/Model/Stock.swift
> +        }
이런 경우 Coffee를 거르지 않고 할 수 있는 방법은 없을까요?

2021-03-03 08:54 UTC, ellyheetov commented on VendingMachineApp/Model/Stock.swift
> +*/
해당 메소드를 사용하고 싶었는데 구현력이 부족해서 완성하지 못했습니다. 혹시라도 나중에 사용하고자 주석으로 남겨 두었습니다...ㅎ

2021-03-03 08:55 UTC, godrm commented on VendingMachineApp/Model/Stock.swift
> +        return products.toDictionary(with : {$0.self})
아무리 한 줄이라도 클로저는 내려서 쓰는게 좋습니다. 클로저 내용만 수정할 때 diff가 더 깔끔하게 볼수도 있습니다. 심지어 회사들 중에서는 매개변수도 한 줄씩 내려서 쓰는 경우도 있습니다. 참고하세요.

2021-03-03 08:55 UTC, godrm commented on VendingMachineApp/Utility/DateUtility.swift
> +        return calendar.compare(self, to: Date(), toGranularity: .day) == .orderedAscending
이런 경우는 기준값을 매개변수로 전달해주는 것도 좋습니다.

2021-03-03 08:56 UTC, merged

2021-03-03 08:57 UTC, ellyheetov commented on VendingMachineApp/Model/Stock.swift
> +        }
products는 Beverage 배열인데, `isHot()`메소드는 하위 클래스에서 가지고 있는 메소드이므로 다운 캐스팅을 하지 않고는 접근할 수가 없었습니다. 혹시 다른 방법이 있을 까요??

2021-03-03 08:58 UTC, ellyheetov commented on VendingMachineApp/Utility/DateUtility.swift
> +        return calendar.compare(self, to: Date(), toGranularity: .day) == .orderedAscending
현재를 기준으로 유통기한이 지났는지 안 지났는지를 확인 해야하므로 기준값은 항상 현재 시각 이라고 생각했습니다. 때문에 매개변수로 넘겨 주지 않았습니다.

2021-03-03 09:02 UTC, godrm commented on VendingMachineApp/Utility/DateUtility.swift
> +        return calendar.compare(self, to: Date(), toGranularity: .day) == .orderedAscending
그쵸 그 현재시각이라는 것도 매개변수로 지정해주면 테스트하기 수월해집니다. 마치 랜덤값을 테스트하는 것과 비슷합니다.

2021-03-03 09:05 UTC, ellyheetov commented on VendingMachineApp/Utility/DateUtility.swift
> +        return calendar.compare(self, to: Date(), toGranularity: .day) == .orderedAscending
그렇군요😃

2021-03-03 09:06 UTC, godrm commented on VendingMachineApp/Model/Stock.swift
> +        }
맞아요. 이 방법도 괜찮습니다. 혹시 다른 방법이 가능하지 않을까 했습니다. 저도 생각해볼게요 :)

2021-03-03 09:07 UTC, godrm commented on VendingMachineApp/Model/Stock.swift
> +*/
커밋에 남겨두지 말고 stash를 하거나 임시로 남겨놓고 커밋에는 최종 작업만 남겨놓으세요.