[okstring / Isaac] Step2 - VendingMachine 설계, 통합 테스트 시나리오
code-squad/swift-vendingmachineapp pull request #253
Opened 2021-03-02 05:33 UTC by okstring

### 스텝별 작업 목록

#### 음료수

- [x] 6가지 종류 음료수 상품을 판매하는 자판기 프로그램을 구현한다.
- [x] 자판기 구조체를 테스트하는 유닛테스트를 추가한다.
- [x] XCTest로 단위 테스트를 위해서 테스트 타깃을 추가하거나 설정한다.
- [x] 음료수 클래스 계층을 음료수 최상위 객체부터 그룹을 만들어서 3단계 이상 구분한다.
- [x] 상속 받은 하위 클래스에도 상위 클래스에 없는 적어도 하나 이상의 속성을 추가한다.
- [x] 추가한 속성에 대한 인터페이스와 함께 추가 인터페이스를 작성한다.
- [x] 음료수 클래스 인터페이스를 테스트하기 위한 테스트 코드를 작성한다.

#### 자판기

- [x] 자판기 금액을 원하는 금액만큼 올리는 메소드

- [x] 특정 상품 인스턴스를 넘겨서 재고를 추가하는 메소드

- [x] 현재 금액으로 구매가능한 음료수 목록을 리턴하는 메소드

- [x] 음료수를 구매하는 메소드

- [x] 잔액을 확인하는 메소드

- [x] 전체 상품 재고를 (사전으로 표현하는) 종류별로 리턴하는 메소드

- [x] 유통기한이 지난 재고만 리턴하는 메소드

- [x] 따뜻한 음료만 리턴하는 메소드

- [x] 시작이후 구매 상품 이력을 배열로 리턴하는 메소드

- [x] 각 메소드 동작을 검증할 수 있는 테스트 함수를 작성한다.

- [x] 전체 코드를 확인할 수 있는 통합 테스트 시나리오를 가지고 동작을 확인한다.

  

### 학습 키워드

- Factory 패턴
- DIP(Dependency Inversion Principle, 의존 관계 역전 원칙)
- 디미터 법칙 
- OCP(Open-Closed Principle, 열림-닫침 원칙)

### 고민과 해결

- 이번 스텝에서는 객체 지향 프로그래밍 시 기본원칙이 되는 것들을 되새기기 위해 부분 적용해보도록 노력했습니다. 특히 애매한 부분은 `StockManagement` 의 메세지가 같은 부류로 묶이지 않는 것 같아 단일책임원칙을 지키기 않는 것 같지만 그렇다고 나눈다고 해서 프로토콜을 따로 쓰이는 모양새가 나오지 않는 듯 하여 합쳐두게 되었습니다.
- test를 한꺼번에 묶어서 했지만 타입별로 나눠서 한다는 것이 아직까지 익숙치 않은 것 같습니다. 일단은 요구사항의 통합 테스트 시나리오라는 키워드처럼 처럼 일련의 과정을 하나의 함수에 넣고 이후 스텝부터 타입별로 테스트를 해보려 합니다.

### 질문거리

- `Drink` (`Fanta`, `BingBananaMilk` 등) 객체를 만들 때  `DrinkFactory` 에서 만들고 있는 모양인데 팩토리패턴이 맞는지 모르겠습니다. 타입이 아닌 enum으로 매개변수를 받아서 아리송한거 같습니다.

2021-03-02 06:49 UTC, godrm requested changes
수고하셨습니다. 다음 피드백을 확인해서 클래스 관계나 하위 타입들을 선언해보세요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/DrinkFactory.swift
> +        case .fanta: return Fanta(flavor: .orange, manufactured: manufactured)
그러네요. 이미 클래스로 선언해놨는데 ProductizationType 로 또 선언하는 것은 불필요합니다.
타입 정보를 값으로 활용하려면 메타 정보가 필요할 겁니다.
인스턴스 >> 클래스(또는 struct) >> 메타 클래스 관계가 성립합니다. 
BingBananaMilk.self 를 값처럼 쓸 수 있고, 비교도 할 수 있습니다. 참고하세요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Coffee.swift
> +    private(set) var isDecaffeinated: Bool
이런 경우는 함유량을 넣고 필요한 경우는 Bool 보다는 범위가 있는 타입으로 하고 비교하는 메소드를 제공하는 게 좋습니다.
예를 들어 메소드를 isDecaffeinated(unit:) 정도로 기준값과 비교하도록 만들면 유연한 구조가 됩니다.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Date.swift
> +        dateFormatter.dateFormat = "yyyyMMdd"
이런 경우도 format을 매개변수로 넘겨주면 유연한 구조가 되겠네요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    private(set) var manufactured: Date
private(set)보다 우선적으로 private을 고려해보세요.
가져갈 수 있다고 생각하면 메소드를 만드는 연습이 안되는 경우가 많습니다.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    }
hash(into:) 와 Equatable == 연산자는 어떻게 다른걸까요? 이름만 같으면 같은 객체일까요?

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/DrinkFactory.swift
> +}
동일한 파일을 다른 곳에서도 본 것 같은데, 어떻게 된 걸까요? 
커밋할 때는 꼭 작업한 파일만 확인하고 올리는 습관을 가지세요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Milk.swift
> +    private(set) var isLowFatMilk: Bool
언급했던 것처럼 Bool 타입을 속성으로 하기 보다는 모델링할 때 속성은 함유량을 넣고 필요한 경우는 Bool 보다는 범위가 있는 타입으로 하고 비교하는 메소드를 제공하는 게 좋습니다.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Productization/CoffeeDrink/BlueBottleColdBrew.swift
> +    }
이 메소드는 지정 생성자일까요 convenience 일까요?

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Productization/CoffeeDrink/BlueBottleColdBrew.swift
> +    }
validate-는 명확한 의도를 표현하지 못하는 것 같네요. 날짜를 지난걸까요? 이전걸까요? 명확한 이름을 표현해주세요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Productization/CoffeeDrink/BlueBottleColdBrew.swift
> +    }
속성이 없는데 그냥 값을 리턴하는건가요?

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Productization/MilkDrink/BingBananaMilk.swift
> +    private(set) var target: Target
enum 타입을 두는 것은 나쁘지 않은데 String 으로 지정한 것은 조금 어색합니다. 특히 all = "" 빈 값은 어떤 의도인지 모르겠어요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Protocol/StockManagement.swift
> +}
이런 시도는 매우 긍정적입니다. 다만 StockManagement 의미가 아래 동작들을 추상적으로 잘 표현하는 지는 고려해보세요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/StockDrink.swift
> +        }
drink.price 를 private(set)으로 처리하면 이렇게 비교하게 됩니다.
private으로 바꾸고 비교하는 메소드를 제공하도록 개선해보세요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/StockDrink.swift
> +            if !drinkProduct.validate(with: now) {
비교하는 메소드는 부정적으로 사용하기 보다는 긍정적으로 사용하는 게 좋습니다. 
bool 타입이 부정일 때 true면 매우 헷갈리는 상황이 됩니다. 그런지 아닌지 확인해보세요.

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/StockDrink.swift
> +    public func toShowStock() -> [Drink: UInt] {
이렇게 Drink 클래스를 사용하면 결국 인스턴스가 들어가야 합니다.
Drink 서브 클래스 타입들이 키로 들어갈 수는 없을까요?

2021-03-02 06:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +    private var coin: Int
coin도 하위 타입으로 선언해보세요.

2021-03-03 05:52 UTC, okstring commented on VendingMachineApp/VendingMachineApp/DrinkFactory.swift
> +        case .fanta: return Fanta(flavor: .orange, manufactured: manufactured)
메타클래스를 활용해 switch문을 만들었습니다. 이런 방법도 있다는게 좋은 것 같습니다만 잘 사용하기 위해서는 메타타입의 정확한 이해와 공부가 필요해보입니다.

2021-03-03 05:52 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Coffee.swift
> +    private(set) var isDecaffeinated: Bool
객체를 설계할 때 좀 더 유연하게 설계해보도록 노력해보겠습니다.

2021-03-03 05:53 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Date.swift
> +        dateFormatter.dateFormat = "yyyyMMdd"
Format을 받아서 유연하게 처리했습니다. 설계 시 항상 염두해야 할 부분인 것 같습니다.

2021-03-03 05:53 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    private(set) var manufactured: Date
넵! 먼저 private로 접근을 해보도록 하겠습니다.

2021-03-03 05:53 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    }
안일하게 생각햇던 것 같습니다. combine으로 경우의 수를 높이고 식별 가능한 속성들을 비교해서 Equatable을 충족했습니다.

2021-03-03 05:53 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/DrinkFactory.swift
> +}
작업의 우선순위를 두지않고 중구난방으로 수정하고 지우고 commit해서 난리가 난 것 같습니다. 앞으로 주의하겠습니다.

2021-03-03 05:53 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Milk.swift
> +    private(set) var isLowFatMilk: Bool
넵! 해당 속성이 수치를 가질 수 있고 비교를 통해 가능하다면 범위가 있는 타입으로 지정하도록 하겠습니다.

2021-03-03 05:54 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Productization/CoffeeDrink/BlueBottleColdBrew.swift
> +    }
지정생성자의 모양을 하고 있지만 쓰임이 잘못된 것 같습니다. 지정생성자를 하나 더 만들고 해당 생성자를 호출하는 간편 생성자를 만들었습니다.

2021-03-03 05:54 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Productization/CoffeeDrink/BlueBottleColdBrew.swift
> +    }
isPastManufactured로 네이밍해봤습니다.

2021-03-03 05:54 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Productization/CoffeeDrink/BlueBottleColdBrew.swift
> +    }
각각 메소드들은 속성을 가지고 있다는 점을 인지하지 못하고 있었던 것 같습니다. 새로운 속성과 함께 메소드를 변경했습니다.

2021-03-03 05:55 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Productization/MilkDrink/BingBananaMilk.swift
> +    private(set) var target: Target
맛이 달라도 같은 객체라고 순간 생각했었던 것 같습니다. Enum string을 활용해 해당 제품 이름을 추가했습니다.

2021-03-03 05:55 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Protocol/StockManagement.swift
> +}
뭔가 프로토콜 입장에서 stock을 관리하는 느낌이어서 StockManagement로 네이밍을 했지만 규약의 느낌이 부족한 것 같습니다. StockManageable로 네이밍을 변경해봤습니다.

2021-03-03 05:55 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/StockDrink.swift
> +        }
수정 완료했습니다 private로 두고 계속해서 연습해보겠습니다.

2021-03-03 05:55 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/StockDrink.swift
> +            if !drinkProduct.validate(with: now) {
Guard문을 활용못하고 있었던 것 같습니다. 또한 Bool 반환 시 주로 쓰일때를 생각해서 설계하도록 하겠습니다. drink에서 쓰이는 메소드를 `isDrinkableFromManufactured`로 바꾸고 로직을 반대로 바꿨습니다.

2021-03-03 05:55 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +    private var coin: Int
CoinCounter 하위타입을 선언하고 프로토콜을 따로 만들었습니다. Get 없이 메소드로 처리했는데 점점 벤딩머신이 코드 양이 많아지는 것 같아 coins를 private(set)으로 변경해도 괜찮은 방법일지 궁금합니다.

2021-03-03 05:56 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/StockDrink.swift
> +    public func toShowStock() -> [Drink: UInt] {
오래 고민해봤지만 리뷰주신 것의 이해를 정확히 못했습니다. `Drink`의 서브클래스라면 `Soda`나 더 하위인 `SeoulStrawberryMilk`, `Fanta`인데 그것들도 넣게 된다면 똑같이 인스턴스를 넣게 되는 모양이라서 의도하신 다른 방법이 있나 궁금합니다.
#### 시도해 본 것
 - `Productization`에 Hashable 채택
   - 이렇게되면 PAT 타입이 되버려 `Productization`을 직접 전달하거나 값을 반환할 수도 없어 3단계 drink들을 해당하는 역할을 못하는 것 같아보였습니다
 - `Productization`을 클래스로 변경
   - 3단계 음료들을 아우르는 슈퍼클래스가 있는데도 따로 상속을 하게 하는 클래스가 이상해보여서 시도하다가 다시 복귀하게 됐습니다..
 - `ObjectIdentifier`: 객체 고유 identifier를 키값으로 가져 딕셔너리로 구현할 수 있었지만 같은 타입의 다른 인스턴스도 구분이 됐습니다. 즉 같은 이름의 음료여도 다르게 카운트가 됐습니다. 의도하신 방법이 이 방법인지 궁금했습니다. 

여러 고민을 해보다 도움을 요청합니다..!

2021-03-03 07:45 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/StockDrink.swift
> +    public func toShowStock() -> [Drink: UInt] {
Dictionary 키값을 Drink 타입으로 선언하면 값은 Drink의 하위 클래스 중에 하나 인스턴스가 들어가겠죠. 
제 말은 Soda 든 SeoulStrawberryMilk, Fanta 든 타입 자체가 들어가면 어떻냐는 겁니다. 
예를 들어 `Dictionary[메타클래스: [Drink]]` 이런 구조로 만들 수 있을까요?
너무 어려우면 그냥 지금처럼 하셔도 됩니다. 꼭 해보자는 건 아닙니다. 넘어갑시다 :)

2021-03-03 08:37 UTC, godrm commented
전부 수정한건가요? 컨펌해주세요.

2021-03-03 08:56 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/StockDrink.swift
> +    public func toShowStock() -> [Drink: UInt] {
앗 그 방법도 가능한 거였군요..! 넵! 메타클래스 개념 정리할 때 따로 만들어보도록 하겠습니다 감사합니다 :)

2021-03-03 08:57 UTC, okstring commented
감사합니다 수정 완료했습니다.

2021-03-03 08:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/DrinkFactory.swift
> +        case .fanta: return Fanta(flavor: .orange, manufactured: manufactured)
타입을 사용했으면 drink.init() 형태가 가능한지 살펴보세요.

2021-03-03 08:59 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Productization/CoffeeDrink/BlueBottleColdBrew.swift
> +    }
이거 바꾼게 diff에서 안 보이네요? 속성을 쓰나요?

2021-03-03 09:00 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Productization/ProductizationType.swift
> +    case fanta = "Fanta"
ProductizationType 이런 타입을 선언하지 않고, 이미 선언한 음료수 클래스 타입들을 활용해보세요.

2021-03-03 09:01 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Productization/SodaDrink/Sanpellegrino.swift
> +                   manufactured: manufactured)
이정도 초기값만 넘기면 지정 생성자라기 보다는 간편 생성자가 됩니다. 
초기값을 주는 것도 외부에서 지정할 수 있는 여지를 줘야 합니다. 그렇지 않으면 하드코딩과 다른게 없습니다. 
팩토리에서 초기값을 주고 생성하는 구조도 생각해보세요.

2021-03-03 09:01 UTC, godrm commented
수고하셨습니다. 다음 단계로 진행해보세요.

2021-03-03 09:01 UTC, merged

2021-03-03 09:16 UTC, okstring reviewed
JK! 왜인지는 모르겠는데🤔 지금 남겨주신 리뷰들이 diff가 첫번째 push 할 때의 내용들이라 제가 새로 작성한 내용이 안들어간 것 같아 오해가 생길 수도 있을 것 같아 남겨드립니다 😭

2021-03-03 09:16 UTC, okstring commented on VendingMachineApp/VendingMachineApp/Model/Productization/CoffeeDrink/BlueBottleColdBrew.swift
> +    }
앗 왜 diff에서 안보일까요 알쏭달쏭 git..😭 `isHot`, `isLowCalorie` 를 Drink에서 구현했습니다. 추가로     `temperature`, `calorie`를 생성자에서 받습니다!
https://github.com/okstring/swift-vendingmachineapp/blob/VendingMachineApp-step2/VendingMachineApp/VendingMachineApp/Model/Drink.swift#L48

2021-03-03 09:43 UTC, godrm commented
네 수정된거면 넘어가세요. 댓글을 남기다보면 이전 상태와 구분이 안되기도 합니다.