[Dumba] - Step02 : 자판기 기본동작
code-squad/swift-vendingmachineapp pull request #254
Opened 2021-03-02 08:21 UTC by ghis22130

**음료수**
- ☑️ 음료수 클래스 계층을 음료수 최상위 객체부터 그룹을 만들어서 3단계 이상 구분한다.
- ☑️ 상속 받은 하위 클래스에도 상위 클래스에 없는 적어도 하나 이상의 속성을 추가한다.
- ☑️ 음료수 클래스 인터페이스를 테스트하기 위한 테스트 코드를 작성한다.
**자판기**
- ☑️ 자판기 금액을 원하는 금액만큼 올리는 메소드
- ☑️ 특정 상품 인스턴스를 넘겨서 재고를 추가하는 메소드
- ☑️ 현재 금액으로 구매가능한 음료수 목록을 리턴하는 메소드
- ☑️ 음료수를 구매하는 메소드
- ☑️ 잔액을 확인하는 메소드
- ☑️ 전체 상품 재고를 (사전으로 표현하는) 종류별로 리턴하는 메소드
- ☑️ 유통기한이 지난 재고만 리턴하는 메소드
- ☑️ 따뜻한 음료만 리턴하는 메소드
- ☑️ 시작이후 구매 상품 이력을 배열로 리턴하는 메소드
- ☑️ 각 메소드 동작을 검증할 수 있는 테스트 함수를 작성한다.
- ☑️ 전체 코드를 확인할 수 있는 통합 테스트 시나리오를 가지고 동작을 확인한다.
=======================================================================================
**해결과정**
- 이미 작성 완료된 상태에서 XCTest를 작성하려 하니 테스트를 할수 있는 부분이 매우 지엽적이고 어떠한 방식으로 해야할지 어려움을 겪었습니다.
- TestScenario 클래스를 작성하여 통합적인 흐름을 살펴보았습니다. TestScenario를 OutputView와 같은 동작을 하는 형식으로 구현해보았습니다.
- 오늘 수업 후 겹쳐져있던 init을 convenience로 바꿔야 함을 인지하였고 그에 따라 변경하였습니다.
- 3단계 하위 객체들에 대한 정보를 enum으로 정리해보았습니다. & VendingMachine 클래스 안 Coin 타입을 nested하게 선언해보았습니다.
- 이전 수업 수강 후 클래스간 의존성을 낮추기 위해 Drink관련 protocol을 선언해보고자 하였으나 이미 너무 꼬인 상태라 진행 하면서 수정을 해보고자 합니다....!
- Dictionary를 구현하기 위해 Drink 객체간 비교를 위한 Hashable, Equatable 프로토콜을 구현해야 했고 이에 따라 구현해 보았습니다.

2021-03-02 09:30 UTC, godrm requested changes
수고하셨습니다. 
다음 피드백을 확인해서 개선해보세요.

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Coffee.swift
> +    private var decaffein: Bool
이런 경우는 함유량을 넣고 필요한 경우는 Bool 보다는 범위가 있는 타입으로 하고 비교하는 메소드를 제공하는 게 좋습니다.  
예를 들어 메소드를 isDecaffeinated(unit:) 정도로 기준값과 비교하도록 만들면 유연한 구조가 됩니다.

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/CocaCola.swift
> +        }
타입별로 용량과 가격까지 지정해버렸네요. Flavor가 추가될 때마다 고쳐야 하는 곳이 capacity(), price() 등등 늘어가게 될겁니다.
이렇게 enum 타입을 쓰기보다는 CocaCola를 상속해서 하위 타입으로 OriginalCoke, CherryCoke, VanillaCoke 타입을 선언하는 것을 생각해보세요.
다른 Flavor가 추가되도 기존 CocaCola나 다른 타입들에 영향이 최소화되도록 만드는 게 좋습니다. 
가격이나 용량을 조정하기도 쉽구요.

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/DrinkDictionry.swift
> +    private (set) var drinkDictionary: Dictionary<Drink, Int>
DrinksDictionary 보다는 다른 이름은 어떨까요? ㅎㅎ 
음료 사전이 되는건가요? 
여기서 사용하는 Drink 타입을 지정하면 키값은 인스턴스가 됩니다.
인스턴스가 아니라 Drink 하위 클래스 타입들을 값으로 쓰려면 어떻게 해야할까요?
메타 클래스라는 정보가 있습니다. Coffee.self 처럼 타입을 값으로 활용할 수 있습니다.

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Drinks.swift
> +    }
여기도 DrinksDictionary를 리턴해야 하는거 아닌가요?

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Georgia.swift
> +
여기는 전혀 속성이 없네요. 그러면 그냥 Coffee 타입으로 대체하면 된다는 겁니다.
하위 클래스는 세부적인 속성이 있어야 합니다.

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Soda.swift
> +    private var zeroCalorie: Bool
decaffein 처럼 함유량을 넣고 필요한 경우는 Bool 보다는 범위가 있는 타입으로 하고 비교하는 메소드를 제공하는 게 좋습니다.

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/VendingMachine.swift
> +    }
돈 단위를 지정해주셨네요. 별개로 Money를 세부 타입으로 선언할 수 있을까요? 
아래 credit 타입을 대체할 수 있을 것 같네요.

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/VendingMachine.swift
> +            return Drink()
구매할 수 없을 때는 흐름 제어를 위해서 Drink() 보다는 다른 방법이 어떨까요? 옵셔널로 한다거나 throw를 한다거나...

2021-03-02 09:30 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/VendingMachine.swift
> +    }
와 하위 타입이 일을 잘 하고 있네요.

2021-03-03 02:01 UTC, ghis22130 commented on VendingMachineApp/VendingMachineApp/Models/Georgia.swift
> +
어라라 이 파일은 삭제 했는데 여기에는 남아있나보네요..아마 지울 때 참조만 지운듯 합니다.. ㅜ

2021-03-03 02:47 UTC, ghis22130 commented
말씀하신 피드백들을 반영해보았습니다.
DrinksDictionary -> DrinksInventory로 수정하였습니다.
다만 키값 조정을 어떤식으로해야할지 도저히 감이 오지 않는데 조금 더 힌트를 주실 수 있을까요?

- equable 메소드 == 을 `lhs.self == rhs.self` 로 선언해보았지만 항상 같은 경우.
- hashable 메소드 hash에 hasher(self)
등으로 해보았지만 모든 하위객체의 타입을 담을 수 있도록 하는 방법이 떠오르지 않습니다...

2021-03-03 02:49 UTC, godrm commented
그렇다면 type(of:) 나 ObjectIdentifier를 찾아서 학습해보세요.

2021-03-03 04:51 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Milk.swift
> +        return fat < 30
이런 비교값은 매개변수로 전달하면 좋습니다.

2021-03-03 04:51 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Models/Money.swift
> +    private (set) var property: Int
이렇게 내부 속성을 Int로 열지않고 Money를 그대로 쓸 수 있는지 고려해보세요.

2021-03-03 04:52 UTC, godrm commented
수고하셨습니다. 다음 단계를 하면서 개선해보세요.

2021-03-03 04:52 UTC, merged