[Zeke]Step1 - 음료수 클래스 계층과 자판기 객체의 행위, XCTest
code-squad/swift-vendingmachineapp pull request #256
Opened 2021-03-02 11:50 UTC by zeke-iOS

- 작업 목록
  - 음료수
    - [x] 음료수 클래스 계층을 최상위 객체부터 3단계 이상 구분
    - [x] 상속받은 하위 클래스에도 상위에 없는 속성 한가지 이상 추가
    - [ ] 추가한 속성에 대한 인터페이스 작성
  - 자판기
    - [x] 원하는만큼 금액 추가하는 메소드
    - [x] 재고 추가 메소드
    - [x] 현재금액으로 구매가능 음료수 리스트 반환 메소드
    - [x] 음료수 구매 메소드
    - [x] 잔액 확인 메소드
    - [x] 종류별로 재고 반환하는 메소드
    - [x] 유통기한 지난 재고 반환하는 메소드
    - [x] 재고중에 따뜻한 음료수 반환하는 메소드
    - [x] 구매상품 이력 반환하는 메소드

 

- 학습 키워드

  - designated init
  - convenience init
  - XCTest
  - 스위프트의 프로토콜과 자바의 인터페이스 차이
  - Hashable 프로토콜
  - Equatable 프로토콜
  
  

- 고민과 해결

  - 전체 상품 재고를 종류별로 반환하기 위해 `Dict`타입을 이용해야 한다. `Dict`타입의 key타입에 Beverage를 대입한 순간 컴파일 에러가 나왔다. 이유인 즉, `Dict`타입의 key타입은 `Hashable`을 채택한 타입만 들어갈 수 있었다. 따라서 Beverage타입에 `Hashable`프로토콜을 채택하였지만 다시 컴파일 에러가 등장하였다. stackoverflow의 한 질의응답을 통해 hash()메소드를 통해 hash값을 제공해야한다는것을 알고 객체의 속성들을 제공하여 문제를 해결하였다.
  - Beverage는 `Hashable`을 사용하기 위해선 `Equatable`프로토콜 또한 채택해야한다. 이유는 `Hashable` 프로토콜은 `Equatable` 프로토콜에서 상속되기 때문에 요구 사항이 충족되어야 한다. 따라서 프로토콜을 따라 타입메소드 '=='를 description 비교를 반환하여 구현하였다.
  

- 부연 설명

  - Drinks클래스 안에 Beverage타입을 배열로 갖는 purchasedDrinks라는 프로퍼티를 생성하여 구매했던 음료수들의 이력을 반환하는 메소드를 구현하였다.
- 질문거리
  - '추가한 속성에 대한 인터페이스 작성'이라는 것은 음료수 및 하위타입들에 대해 개별적으로 프로토콜을 하나씩 생성하는건가요??

2021-03-02 14:21 UTC, godrm requested changes
수고하셨습니다. 다음 피드백을 확인해보세요.

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
> +    private var expirationDate: Date
속성 이름에 타입 이름을 그대로 붙이지 않아도 충분히 유추할 수 있습니다. 
Date를 과감하게 빼보세요.

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
>      }
여기 메소드들 사이는 줄 간격이 떨어지지 않았네요. 의도한 것일까요?
빈공백이나 줄도 일관성 있게 작성해주는 게 좋습니다.

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
>  }
- Equatable과 Hashable 은 어떤 차이가 있는건가요? 
- 특히 description을 로직 구현하는 데 사용하지마세요. 나쁜 습관입니다. 속성값과 비교하는 게 좋습니다.

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/CashManagementSystem.swift
> +    }
여기 선언한 함수들 시그니처에 줄간격이 들쭉날쭉 합니다. 사소한 거지만 가독성을 떨어뜨립니다. 일관성 있게 작성하세요.

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/CashManagementSystem.swift
> +    }
이정도 타입이면 내부 cash를 return 하지 않고 그대로 (이름은 좀 거창하지만) CashManagementSystem을 타입으로 사용해도 좋을 것 같습니다. 세부적인 타입을 만들면 그대로 쓰려고 노력해보세요.

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/CashManagementSystem.swift
> +        return drinks.showListForPurchase(with: cash)
이 메소드는 좀 오버같습니다. Drinks에 cash를 넘기는 게 어떨까요? 
잔돈 시스템에 음료수 목록을 전달하는 게 어색합니다.

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Coffee/Coffee.swift
> +        return self.caffeineContent >= 0.15
이런 비교식은 기준값을 상수로 선언하고 매개변수로 전달하는 게 좋습니다.
특히 0.15 같은 Double 실수값을 비교할 때는 오차를 같이 고려하셔야 합니다. 
특정한 값에 따라서 같을수도 다를 수도 있습니다. 오차 범위에 대해 학습해보세요.

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drinks.swift
> +    private var purchasedDrinks: [Beverage]
얼핏 보면 이 두 가지를 모두 쓰는 메소드보다 하나씩 쓰는 메소드가 더 많은 거 아닐까요?
두 속성이 얼마나 관련이 있을까요?

2021-03-02 14:21 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
>      }
전체적으로 자판기 코드는 매우 깔끔하네요.
여기서 리턴하는 [Beverage] 대신에 Drinks를 사용할 수는 없는건가요? 어떤 차이가 있을까요?

2021-03-03 05:48 UTC, zeke-iOS commented on VendingMachineApp/VendingMachineApp/Model/CashManagementSystem.swift
> +    }
내부의 cash를 return하지 않고 그대로 타입을 사용한다. 문장을 계속 읽고있지만 어떻게해야할지 감이 잘 안옵니다🥲 checkBalance()의 반환타입을 CashManagementSystem으로 하고 맞춰서 구현하면될까요?

2021-03-03 07:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/CashManagementSystem.swift
> +    }
네 말하자면 그런거죠. 그러면 그 타입을 그대로 다른 곳에서도 사용하고, 메소드로 접근하게 될테니까요.
카드 게임에서 Rank나 Suit를 빼서 넘겨주는 게 아니라 Card 를 넘겨주는 것처럼요

2021-03-03 07:47 UTC, godrm commented
@zeke-iOS 수정이 끝난건가요? 확인해서 머지하면 되나요?

2021-03-03 07:49 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
>      private var expirationDate: Date
`manufacture`는 날짜 느낌이 부족하니까 manufacturedAt 처럼 표현해도 좋을 것 같습니다. 
expirationDate도 개선해보세요.

2021-03-03 08:23 UTC, zeke-iOS commented
수정하였습니다😀

## 바뀐것

- dateOfManufacture의 이름 변경 -> 다시 변경하겠습니다!!
- 줄바꿈, 줄 간격 수정 -> XCode를 화면의 반만 사용하다보니 띄어쓰기가 눈에 잘 안띄었네요 유의하겠습니다.
- hashable 프로토콜 수정
- CashManagementSystem 객체에 있던 showListForPurchase()는 어색하다는것을 확인하였습니다. 따라서 Drinks로 옮겼습니다.
- isHighCaffeine() 수정 -> 소수점 2자리로 제한하는것이 오차 범위를 줄이는것이라고 생각하였습니다. 이러한 방향이 맞는지 사실 잘 모르겠습니다.
- PurchasedList Class생성 -> 기존에 Drinks에 들어있었던 속성이지만 메소드에서 같이 사용되지 않아 연관성이 없으니 따로 class로 분리하였습니다.
- 자판기의 메소드들은 [Beverage]타입으로 반환되었는데, 이는 활용성이 너무나 떨어진다. 생성한 세부타입을 적극적으로 이용하지 못한다. 따라서 기존 생성한 Drinks, PurchasedList, CashManagementSystem 타입으로 반환하게 하였습니다.
- 반환타입이 바뀜에 따라 XCTest도 수정해야한다. 새로 생성한 타입들에 Equatable을 채택하여 XCTAssertEqual을 이용할 수 있게 되었습니다.

2021-03-03 08:36 UTC, godrm commented
네. 다음 단계를 진행해봅시다.

2021-03-03 08:36 UTC, merged