[Hong] Step2 - 팩토리 메서드 패턴, 음료수 3계층 설계
code-squad/swift-vendingmachineapp pull request #264
Opened 2021-03-03 12:23 UTC by HongzCloud

- 작업목록

  - 음료수

    - [x] 음료수 3계층으로 구분

    - [x] 하위 클래스에 속성 한개이상 추가

    - [x] 추가한 속성에 대한 인터페이스 작성 (3개만 작성했음)

  - 자판기

    - [x] 원하는 금액만큼 추가 기능

    - [x] 음료 재고 추가

    - [x] 현재 금액으로 살 수 있는 음료 목록 반환 기능

    - [x] 음료수 구매 기능

    - [x] 잔액 확인 기능

    - [x] 종류별 재고(사전형태)로 반환 기능

    - [x] 유통기한 지난 음료 목록 반환 기능

    - [x] 뜨거운 음료수 목록 반환 기능

    - [x] 음료 구매 이력 반환 기능

- 학습 키워드
  - 심플 팩토리, 팩토리 메소드 패턴, 추상 팩토리 패턴
  - Designated init, Convenience init
  - XCTest
  - 클래스타입 dictionary에 넣는 법 : Hashable 프로토콜 채택

- 고민과 해결
  - 구글에 팩토리 패턴이라고 검색하면 여러 코드들이 나왔습니다. 하지만 글쓴이마다 설계가 다 달랐고 언어마다 또 조금씩 달라서 보기 힘들었습니다. 어떤 사람은 추상 팩토리 패턴이라 하는것이 다른 글에서는 팩토리 메소드 패턴이라고 하고 그 반대경우도 있고 찾아보면 찾아볼수록 미궁에 빠져들었습니다. 그래서 결국 공통적으로 말하는 클래스 다이어그램을 보며 내 코드에 적용해 보았습니다.

- 질문거리

    convenience init은 일부를 기본값으로 지정해놓기 위해 사용하는 것 같은데
  Designated init으로 그냥 init(name: String = "바나나우유") 이렇게 해서 
  기본값 지정하면 될거 같은데 왜 만들었는지 아직 의문입니다.
  이니셜라이저의 목적이 얼로케이션(객체생성)이랑 변수값 초기화 2개라고 하셨는데
  역할을 분리해서 변수값 초기화 목적으로 convenience init 쓰는 건가 싶기도 합니다.

2021-03-04 05:46 UTC, godrm requested changes
수고하셨습니다. 다음 피드백을 확인해서 개선하고 다음 단계로 넘어가겠습니다.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
> +    private(set) var manufacturedAt: Date
객체 속성을 가져갈 수 있으면 상위 모듈에서 값을 처리하는 로직이 생기게 됩니다. 
우선적으로 private를 고려하시고 정말 딱 값을 처리하지 않는 경우가 가져가도록 열어보세요.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
> +    func checkHot() -> Bool
checkHot() 어떤 동작인까요? Bool 타입을 리턴하는 경우는 is-, has-, can-, should- 등 보조 동사를 붙이는 경우가 많습니다.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
> +    func expirationValidate() -> Bool
유통기한을 지난 것이 true일까요 안 지난것이 true일까요. 유추하기 쉬운 표현으로 써보세요.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Date.swift
> +        return format.string(from: self)
이런 메소드는 내부에 하드코딩하는 속성을 매개변수로 넘겨주면 테스트 가능하고 유연한 함수가 됩니다.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Inventory.swift
> +    }
아마도 이렇게 전체를 description으로 제공할 로직이 필요하던가요? 
description은 매우 보조적인 수단입니다. 로직과 상관없이 정보를 출력하는 정도로만 활용하세요.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Level2/Coffee.swift
> +    private var isHot: Bool
내부 속성을 Bool 지정하는 경우는 명확하게 두 가지로만 나뉘는 경우에 사용하세요.
예를 들어 이런 값은 temperature 온도를 값으로 갖고 있고, isHot()을 기준값보다 높냐 낮냐로 판단해주는 메소드를 제공하는 게 좋습니다.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Level2/Level3/BananaMilk.swift
> +    private var hasDoraemonSticker: Bool
ㅎㅎ 이게 바나나우유에서 중요한 속성이었군요!

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Level2/Level3/Coke.swift
> +    private var hasCalorie: Bool
칼로리나 함유량도 hot과 마찬가지로 객체 내부에서는 좀더 세부적인 값을 갖고 있으면서
메소드로 판단할 수 있도록 하는게 좋습니다.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Level2/Milk.swift
> +    private var expiredAt: Date
expiredAt는 모든 Beverage가 필요한 건 아닌가보죠?

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/PurchaseHistory.swift
> +    private(set) var beverages: [Beverage?]
[Beverage?] 는 [Beverage] 와 다른 점이 뭘까요?
옵셔널 배열이 필요한 이유가 있나요?

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +
자판기 정보가 인벤토리가 전부인가요?

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +        purchaseHistory.appendPurchaseHistory(beverage: inventory.takeOutBeverage(beverage, paymentManager: paymentManager))
매개변수 이름을 숨기는 것보다는 put(in money: Int) 형태로 함수 이름과 매개 변수를 하나의 이름으로 간주하는 게 좋습니다.

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +    public func showAllBeverageList() -> [Beverage: Int] {
재고를 [Beverage.Type : [Beverage]] 형태로 표현할 수 있을까요?

2021-03-04 05:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/ViewController.swift
> +        let beverage3 = CoffeeFactory().create()
팩토리도 메타 클래스를 활용해서 하나로 합칠 수 있을까요?

2021-03-05 07:18 UTC, HongzCloud commented on VendingMachineApp/VendingMachineApp/Model/Level2/Milk.swift
> +    private var expiredAt: Date
넵. 원래 우유에만 있도록 했는데 음료전체에 유통기한이 있는게 맞는거 같아서 다시 옮겼습니다.

2021-03-05 07:20 UTC, HongzCloud commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +    public func showAllBeverageList() -> [Beverage: Int] {
Beverage.Type 그냥 넣으니까 Hashable하지 않다고해서
[ObjectIdentifier : [Beverage]]로 넣어주었습니다.

2021-03-05 07:23 UTC, HongzCloud commented on VendingMachineApp/VendingMachineApp/ViewController.swift
> +        let beverage3 = CoffeeFactory().create()
팩토리 메타클래스를 매개변수로 받아 객체를 생성하는 FactoryManager 상위 모듈을 만들었습니다.

2021-03-05 07:25 UTC, HongzCloud commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +
음.. 필요 없는 것 같은데 습관적으로 만든 것 같습니다. 출력해서 확인해보지 않을 decription은 삭제했습니다.

2021-03-05 07:28 UTC, HongzCloud commented on VendingMachineApp/VendingMachineApp/Model/PurchaseHistory.swift
> +    private(set) var beverages: [Beverage?]
음료수 꺼내올 때 nil이 나올수도 있어서 nil도 넣어주고 음료도 넣어주고 했는데
값 가져갈 때 나중에 컴팩트맵으로 nil 제거 해주었어서..
처음부터 음료수 꺼내오는데 실패하면 안들어가도록 타입 변경했습니다.

2021-03-05 07:31 UTC, HongzCloud commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
> +    func checkHot() -> Bool
변경했습니다. 😄

2021-03-05 07:32 UTC, godrm commented on VendingMachineApp/VendingMachineApp/BeverageFactory.swift
> +        return type.self.create()
팩토리 타입을 구분했네요. 팩토리 자체는 중요한 요구사항은 아니었으니 이렇게 할 수 있으면 된 것 같습니다.

2021-03-05 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverage.swift
> +    func isExpired() -> Bool
이런 비교하는 메소드는 매개변수를 활용하는 게 좋습니다. 
기준값을 넘겨줄 수 있고, 기준에 맞춰서 비교해서 결과를 넘겨주면 테스트도 수월해집니다.

2021-03-05 07:34 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverages.swift
> +    public func take(out beverage: Beverage, for paymentManager: PaymentManager) -> Beverage? {
이 부분이 조금 이상하지는 않은가요? Beverage 인스턴스를 리턴하는데 이미 매개변수에 인스턴스를 넘겨주니까요. 
매개변수가 메타 클래스가 되면 어떤가요?

2021-03-05 07:34 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Beverages.swift
> +    public func showAllBeverageList() -> [ObjectIdentifier : [Beverage]] {
네 그래야 키값으로 구분이되죠.
다만 이렇게 타입이 복잡해지면 `[ObjectIdentifier : [Beverage]]` 이 자체도 세부 타입으로 정하면 더 좋습니다.

2021-03-05 07:35 UTC, godrm commented
수고하셨습니다. 다음 단계를 진행하면서 같이 개선해보세요.

2021-03-05 07:35 UTC, merged