[yj / pss327] Step2 - VendingMachineApp 클래스 3계층 생성 및 메소드 구현
code-squad/swift-vendingmachineapp pull request #267
Opened 2021-03-03 14:09 UTC by pss327

### 요구사항

- 음료수 class - 3단계 계층구조 작성
- 음료수를 구매하는 메소드
- 따뜻한 음료만 리턴하는 메소드
- 유통기한이 지난 재고만 리턴하는 메소드
- 전체 상품 재고를 (사전으로 표현하는) 종류별로 리턴하는 메소드
- 현재 금액으로 구매가능한 음료수 목록을 리턴하는 메소드
- 시작이후 구매 상품 이력을 배열로 리턴하는 메소드
- 잔액을 확인하는 메소드
- 자판기 금액을 원하는 금액만큼 올리는 메소드
- 특정 상품 인스턴스를 넘겨서 재고를 추가하는 메소드
### 학습키워드
- 상속, Protocol(프로토콜), 클로저, 인터페이스, initializer

2021-03-04 05:58 UTC, godrm requested changes
수고하셨습니다. 다음 피드백을 확인해서 개선해보세요.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Drinks.swift
> +    private var drinksHistory: [Drink]
아마도 이 타입에서는 drinks와 drinksHistory를 각각 사용하는 메소드가 그룹으로 나눠질 겁니다. 
그렇다면 두 개를 서로 다른 타입으로 분리하는 게 낫지 않을까 고민해보세요.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/MainHomeController.swift
> +                                Coffee.init(isDecaffeinated: true, isHot: true, isCoffeeBrandName: .Cantata, brand: "맥심", capacity: 4000, price: 3000, name: "TOP아메리카노", madeDate: Date(), beverageType
이렇게 세부 객체를 만드는 역할을 팩토리라고 부릅니다. 팩토리 메소드 패턴을 학습해보고 음료수를 생성하는 팩토리를 만들어보세요.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Coffee/Cantata.swift
> +        super.init(isDecaffeinated: isDecaffeinated,isHot: isHot, isCoffeeBrandName: isCoffeeBrandName, brand: brand, capacity: capacity, price: price, name: name, madeDate: madeDate, beverageType: B
Cantata 타입이 Coffee 와 다른 점이 무엇일까요? 이렇게 override만 하는 것은 Coffee를 그대로 사용해도 된다는 의미입니다.
Cantata 타입만이 가지는 속성과 속성을 다루는 메소드가 있어야 서브 클래스로 의미가 있습니다. 
세부적인 속성을 선언해보세요. 그게 2단계에서 가장 중요한 경험중에 하나입니다.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Coffee/Coffee.swift
> +    private var isDecaffeinated: Bool
모델에 속성 Bool 타입은 좀 더 신중하게 고려하세요.  
이런 경우 내부 속성은 decaffeine을 범위있는 값으로 저장하고 isDecaffeinated() 을 메소드로 제공해주는 게 좋습니다.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Coffee/Coffee.swift
> +    }
이 메소드는 이상한데요? isLowCalorie가 isDecaffeinated 속성과 관련이 있나요?

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +
BeverageType는 서브 클래스로 Milk, Soda, Coffee를 만들기 때문에 의미가 없는 타입니다.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    private let beverageType:BeverageType
이런 속성은 서브 클래스를 만들면 필요없는 속성입니다.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
>      private let madeDate : Date
date라는 타입 이름을 속성 이름에 붙이지 말고 역할을 명확하게 표현하도록 노력하세요.
manufacturedAt 정도로 표현하기도 합니다. 참고하세요.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    }
이 메소드도 다형성으로 대체가 가능합니다.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Milk/ChocolateMilk.swift
> +    private let isContainChocolate:Bool
함유량을 포함하는 정보도 객체 내부는 더 상세한 정보를 갖고 있고 메소드로 판단하는 게 좋습니다.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Soda/Cola.swift
> +    private let inBottle: Bool
이 속성도 세부적으로 병콜라, 캔콜라로 만드는 게 더 좋을 것 같은 속성이네요.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Payment.swift
> +    }
타입을 선언할 때 `:` 이전에 이후에 어떤 경우는 붙이고, 어떤 경우는 띄어쓰고 있습니다.
일관성 있게 작성해보세요.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Protocol/HotableProtocol.swift
> +import Foundation
이 파일은 전혀 사용하지 않는 것 같습니다.
커밋할 때는 작업한 파일만 선택해서 커밋하는 습관을 가지세요.

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachine.swift
> +    private var drinks : [Drink]
Drinks 라는 타입을 만들었던 것 같은데 왜 정작 VendingMachine에서는 안 쓰는 걸까요?

2021-03-04 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineAppTests/VendingMachineAppTests.swift
> +
테스트 함수도 이제 추가해보세요.

2021-03-04 09:19 UTC, pss327 commented on VendingMachineApp/VendingMachineApp/Model/Coffee/Coffee.swift
> +    }
isLowCalorie가  isDecaffeinated 속성과 관련이 있습니다. 메소드 명을 변경하도록 하겠습니다.

2021-03-04 09:20 UTC, pss327 commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +
삭제하도록 하겠습니다.

2021-03-04 09:20 UTC, pss327 commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
> +    private let beverageType:BeverageType
삭제하도록 하겠습니다.

2021-03-05 17:57 UTC, pss327 commented on VendingMachineApp/VendingMachineApp/Model/Drink.swift
>      private let madeDate : Date
속성명 madeDate를 manufacturedAt로 변경하겠습니다.

2021-03-06 05:02 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/Coffee/Coffee.swift
> +    }
오잉? 디카페인이면 칼로리가 낮다는 의미인가요?

2021-03-06 05:05 UTC, godrm commented
우여곡절이 긴 단계였던 것 같습니다. 마무리하고 다음 단계를 하면서 계속 개선해보세요.

2021-03-06 05:05 UTC, merged