[ZG] Step2 - 각 클래스 별 책임 분배, 메소드 결정, 팩토리 메서드 학습
code-squad/swift-vendingmachineapp pull request #268
Opened 2021-03-04 05:59 UTC by jhpark-ZG

### Step2 작업 목록

* 음료수 관련
- [x] 음료를 상속하는 서브 클래스 설계
- [x] 하위 클래스의 속성 추가
- [x] 속성에 대한 인터페이스 작성

* 자판기 관련
- [x] 자판기 금액 증가 메소드
- [x] 특정 상품 증가 메소드
- [x] 현재 금액으로 구매 가능 음료 목록 반환하는 메소드
- [x] 음료수 구매 관련 메소드
- [x] 잔액 확인 메소드
- [x] 전체 상품 재고 반환하는 메소드
- [x] 유통기한이 지난 재고만 리턴하는 메소드
- [x] 따뜻한 음료만 리턴하는 메소드
- [x] 시작이후 구매 상품 이력을 배열로 리턴하는 메소드

* 테스트 함수 관련
- [x] 구매 가능한 음료수 목록 반환하는 메소드
- [x] 따뜻한 음료만 반환하는 메소드
- [x] 유통기한이 지나지 않은 음료수만 리턴하는 메소드

### 학습 키워드

* 클래스별 역할 책임 분배
* FactoryMethod 관련
* 다운 캐스팅 관련

### 고민과 해결

* vendingMachine에 메소드를 추가할 때, 매개변수로 최상위 클래스만 넣으려고 노력했습니다. 처음엔 다운 캐스팅, 옵셔널 바인딩을 활용하여 매개변수로 전달된 클래스의 서브 클래스는 무엇인가를 한 함수에서 모두 처리하도록 하였습니다. if문이 다수 나와서 부적절함을 느꼈고, 음료수를 자판기가 추가하는 것이 아닌 음료수가 자판기에 들어가는 방식으로 처리하였습니다.

* FactroyMethod에 대해서 학습하고 구현해봤는데, 제대로 구현했는지 모르겠습니다. 학습한 바로는 "서브클래스가 생성되는 시기만 알뿐, 무엇이 생성되는지는 모르기 때문에, 생성 책임을 서브클래스에게 맡긴다." 라고 알고 있는데요. 서브클래스에서 init()이 이미 생성 책임을 담당하고 있는 것이 아닌 지 명확하게 판단이 안됐습니다. 일단 찾아보고 비슷하게는 만들어봤는데 잘 못 구현해서 그런지, 가져다 주는 이점이 무엇인지 잘 모르겠습니다. 

### 질문 사항

* FactoryMethod가 제대로 구현이 되었는 지 확인 부탁드립니다. 만약 제대로 구현한 것이라면 현 코드상에서 어떠한 이점이 있는 지, 구현이 제대로 안되었다면 어느 부분에 대한 개선이 필요한 지 힌트 부탁드립니다.

항상 감사합니다. JK

2021-03-04 06:22 UTC, godrm requested changes
다음 피드백을 확인해서 음료수를 다루는 객체부터 서브 클래스까지 개선해보세요.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/BananaMilk.swift
> +    }
이런 메소드는 좋지 않습니다. 이 관계가 필요할 것 같지만, 이건 하위 모델이 할 역할이 아닙니다. 
어느 자판기에 들어갈 지 몰라야 합니다.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/BananaMilk.swift
> +    let sugarContent : Int
이런 속성이 있으면 그 값을 그대로 제공해주기보다는 메소드로 기능을 제공해주는 게 좋습니다.
예를 들어 무가당인가? 아닌가 판단해준다거나 그런 메소드를 같이 생각해보세요.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Beverage.swift
> +        return false
다음과 같은 측면을 고려해보세요.
- isValidate()는 그 날짜보다 지난걸까요? 이전일까요? 좀 더 구체적으로 표현이 가능할까요?
- 캘린더를 생성하고 비교하는 것은 Date 타입에서 해야할 일입니다. Date에게 기준 날짜를 알려주고 비교하는 메소드가 있으면 어떨까요? 
- 조건을 비교해서 return 하는 경우는 `return validate > date` 처럼 조건식을 그대로 쓰는 게 읽기 좋습니다.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Beverage.swift
> +        return false
이런 경우는 기준값을 외부에서 매개변수로 넘겨줄 수 있고, 70 대신에 상수로 선언해놓는 게 좋습니다.
그래야 유연한 함수가 되고 테스트 가능합니다.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Beverage.swift
> +    }
구현하지 않을 메소드가 있네요!

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/BeverageCreater.swift
> +    }
이상하지 않은가요? product가 이미 Beverage 인스턴스인데 Beverage 인스턴스를 리턴하는 거면 그냥 product과 같은걸까요?

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/CaffeLatte.swift
> +    let sugar : Bool
모델에 속성 Bool 타입은 좀 더 신중하게 고려하세요.  
이런 경우 내부 속성은 sugar 함유량을 범위있는 값으로 저장하고, 예를 들어 무가당인지 고함유인지를 메소드로 제공해주는 게 좋습니다.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Coffee.swift
> +
이 두 속성은 뭐가 다른걸까요? caffeineContent가 0보다 크면 Bool 값도 자동으로 바뀌나요?

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Date.swift
> +    }
이 메소드는 Date 타입 속성과 관련이 없이 매개변수에만 의존하는 건가요?
static으로 선언해도 되나요? 아니면 매개변수 date 대신에 self를 맨 마지막에 넣을 수 있나요?

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Date.swift
>      }
이 메소드는 Date를 생성하는 메소드네요. init()과 뭐가 다를까요?

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Money.swift
> +    }
내부 속성인데 Int를 return 하는 것은 큰 의미가 없습니다. 
Money를 선언했으면 돈을 표현하는 곳에서 Int 대신에 Money 인스턴스를 쓰도록 해보세요.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachine.swift
> +    private var bought : [Beverage]
아이쿠 LSP를 활용해보세요. 수퍼 클래스는 서브 클래스를 대표해서 대체가 가능합니다. 그래서 Beverage를 만든거니까요.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachine.swift
> +        }
구매하는 메소드도 타입 정보를 활용하도록 하나로 합쳐보세요!

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachine.swift
>      }
여기 있는 addXXX 메소드들도 타입 정보를 활용해서 합쳐보세요.

2021-03-04 06:22 UTC, godrm commented on VendingMachineApp/VendingMachineAppTests/VendingMachineAppTests.swift
> +        XCTAssertEqual(vendingMachine.isValidate(), isValidate)
테스트 함수는 함수 하나가 하나를 테스트하는 게 좋습니다. 지금처럼 함수 하나에 모든것을 다 쓰려는 게 아닙니다.

2021-03-06 00:12 UTC, jhpark-ZG commented on VendingMachineApp/VendingMachineApp/Beverage.swift
> +        return false
* 많이 고민해봤는데 구체적인 표현이란 변수의 표현을 말씀하시는 거 같아서 일단 변수의 표현을 수정하였습니다. 혹시 이게 아니라면 구체적인 표현이란 어떤건지 알 수 있을까요?

2021-03-06 00:15 UTC, jhpark-ZG commented on VendingMachineApp/VendingMachineApp/BeverageCreater.swift
> +    }
다시 구현 했는데 검토 부탁드립니다. 아직도 팩토리 메소드를 구현 했을때의 이점이 명확하게 다가오지 않는데, 재 설계 할때 이점이 있을까요? 예를 들어 "자판기에 넣을 음료가 많이 바뀌어서 혹은 자판기가 추가 되었는 데 비슷하지만 다른 음료가 들어간다면 protocol로 선언해놓은 음료 만드는 메소드를 상속하여 다시 만들어주기만 하면 된다."에 이점이 있는 것으로 지금은 생각하고 있습니다.

2021-03-06 00:18 UTC, jhpark-ZG commented on VendingMachineApp/VendingMachineApp/CaffeLatte.swift
> +    let sugar : Bool
* sugar -> sugarcontent : Int로 변경하고
* sugar : bool 을 그대로 유지한 후에,
* isSugarfree(sugar : Int) -> bool로 sugar의 값을 결정하려고 했습니다.
* init에서 sugar = isSuagrfree(init의 매개변수 sugar)로 초기화 하려고 했으나, super.init후에 메소드를 써야 하는 것 같아서 선언과 동시에 false로 한번 초기화 하였습니다. 이와 같은 방법이 권장 되지 않는 걸로 알고 있는데, 혹시 이와 같은 상황에 더 좋은 방법이 있을까요?

2021-03-06 00:19 UTC, jhpark-ZG commented on VendingMachineApp/VendingMachineApp/Coffee.swift
> +
관련 메소드를 추가하여 초기화할 때 관여하도록 하였습니다. 다만, 이런 방식이 초기화 단계에 권장되지 않는 방법인지 잘 모르겠습니다.

2021-03-06 00:37 UTC, jhpark-ZG commented on VendingMachineApp/VendingMachineApp/Date.swift
> +    }
Date 관련 함수가 잘 이해되지 않아 일단 동작하니까 저렇게 썼었는데, 다시 보니 정말 이상한 코드여서 전부 다시 수정하였습니다. 수정한 함수는 전 함수보단 덜 어색한 것 같습니다.
static으로 선언..은 사실 판단 기준을 잘 모르겠습니다. 제가 아는 지식 내에서는
* 어느 곳에서나 가져다 사용해야 하는 경우
* 1의 조건을 만족하면서 보안에 위배되지 않는 경우
* 내부 속성과 의존성이 없는 경우
인 것 같은데 1번을 만족하는가? 에서 의문이 들어 사용하지 않았습니다. static을 사용해야 했었을까요?

2021-03-06 04:59 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Beverage.swift
> +        return false
isValidate()가 어떤 의미냐는거죠. 번역해보면 검증하기? 검사하기? 무엇을 어떤 기준에서 검사한걸까요? 그게 명확하지 않다는 겁니다.
return 결과값이 어떤 것을 의미하는지 유추하기 어려워서요. true이면 (어떤) 검사가 통과된건가요? 그걸 정확하게 표현할 단어가 더 구체적인 단어였으면 좋겠습니다.

2021-03-06 05:01 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Date.swift
> +    }
쉽게 생각해보면 인스턴스를 생성하기 이전에 호출해야만 하느냐, 인스턴스를 생성한다는 것은 내부 속성을 사용하는 메소드를 사용한다는 건데 그걸 잘 쓰고 있는가... 이런 기준들을 고려해보세요.

2021-03-06 05:02 UTC, godrm commented
수정이 완료된건가요?

2021-03-06 06:38 UTC, godrm commented on VendingMachineApp/VendingMachineApp/BeverageCreater.swift
> +    }
여기 있는 메소드들을 타입별로 만들지 않거나 다형성을 통해 호출할 수 있으면 더 좋을 것 같습니다. 참고하세요.

2021-03-06 06:40 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Beverages.swift
> +    }
beverageValidate()라는 의미가 음료수를 검사하기, 혹은 검증하기 무엇을 검증하는지 이해하기 어렵습니다.
그리고 동사와 목적어가 뒤집혀있네요. 동사로 시작하도록 만들고 내부 구현을 몰라도 유추가 가능하면 좋겠습니다.

2021-03-06 06:41 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Beverages.swift
> +    func comparePrice(money : Money) -> [Beverage]{
comparePrice()도 돈을 기준으로 작은 것인지, 같은 것인지, 높은 것인지 구분이 어렵네요. 더 정확하고 구체적인 동작을 표현하면 좋겠습니다.

2021-03-06 06:41 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Cider.swift
> +    private let HIGHCONTENT : Int
이 속성은 왜 모두 대문자일까요?

2021-03-06 06:42 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Date.swift
> +        return Date().yyyyMMddFormat().date(from: stringdate) ?? Date()
이렇게 구현하면 이 함수를 어떤 것을 테스트해야 할까요?
기대하는 동작이 잘 동작했는지, 실패했는지 확인할 수 있을까요?

2021-03-06 06:44 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Hot6.swift
> +    }
타우린 함유량을 값으로 보관하고 있고, 그 용량이 얼마나 포함되어 있는지, 없는지 판단해주는 메소드도 같이 제공되는 게 좋겠습니다. 
속성과 메소드는 항상 같이 선언하게 되는 편이니까요.

2021-03-06 06:45 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Soda.swift
> +        return sugar < 1
isSugarfree() 메소드는 이상합니다. 내부 sugar 속성을 안쓰는 메소드네요?
더구나 기준값을 지정할 수 없고 매개변수만 비교하는 메소드인가요?  뭔가 동작이 어색합니다.

2021-03-06 06:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/StrawBerryMilk.swift
> +        return self.StrawBerryContent > self.HIGHCONTENT
상수로 선언한 것도 매개변수를 활용하는 게 좋습니다. 그걸 그대로 비교하자는 게 아닙니다.
이 메소드를 테스트한다고 생각해보세요.

2021-03-06 06:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachine.swift
> +    private var beverages : Beverages
타입이름과 속성 이름이 같아지면 뭔가 어색합니다. 타입은 좀 더 추상적이고, 속성은 좀 더 구체적인 역할이 되는 경우가 좋습니다.

2021-03-06 06:47 UTC, merged