[Elly] step3 - 미완성
code-squad/swift-vendingmachineapp pull request #278
Opened 2021-03-08 06:54 UTC by ellyheetov

JK😃 아직 Step 3 기능이 모두 구현되지는 않았지만, 
의미없이 복잡한 코드를 만들어 가는 것이 아닌지 의문이 들어 중간 점검차 PR 보내드립니다.

# 프로그래밍 요구사항
- [x] 각 상품에 대한 재고 추가 버튼을 추가한다.
- [x] 각 상품에 대한 이미지를 추가한다.
- [x] 각 상품에 대한 재고 레이블을 추가한다.
- [x] 1000원, 5000원 금액을 입력하는 버튼을 추가한다. 
- [x] 현재 잔액을 표시할 레이블을 추가한다.
- [x] 각 상품의 재고 추가 버튼을 누르면 각 상품 재고를 추가하도록 코드를 구현한다.
- [ ] 재고 추가 버튼을 누르고 나면 전체 레이블을 다시 표시한다.
- [ ] 금액 입력 버튼을 누르면 해당 금액을 추가하도록 코드를 구현한다.
- [ ] 금액을 추가하고 나면 잔액 레이블을 다시 표시한다.

# 고민 사항🤷🏻‍♀️
- **Beverage.Type을 Dictionary의 Key값으로 사용하고자 했습니다.**
Beverage.Type은 Hashable하지 않기 때문에 Key로 사용할 수 없었습니다. Beverage.Type을 확장하여 hashable하도록 만들려고 했으나, 메타 타입은 확장하여 사용 할 수 없습니다. ObjectIdentifier(Beverage.self) 를 사용하면 Key값으로 사용 할 수 있으나, 이는 ObjectIdentifier가 Key값이 되므로 Type을 키값으로 이용하는 것이 아닙니다.  Hashable하지 않은 메타타입자체를 키값으로 사용하기 위해서는, Dictionary를 확장해야 했습니다. 하지만, 이는 Beverage 객체를 더욱 복잡하게 만드는 결과를 낳게 되었습니다. 때문에, 임시적으로 ObjectIdentifier를 Key로 사용하는 구조를 남겨두었습니다.

- **모든 뷰를 Code로 작성하였습니다.** 
스토리 보드로 작업하는 것이 비교적 익숙하여 코드로 작성하는 방법을 배우고자, 코드로 구성하였습니다. vendingmachine의 값을 앱이 실행되는 동안 유지시키기 위해 AppDelegate를 이용하였습니다. 현재 화면 상에서 버튼을 클릭하면 vendingmachine에 잔액 추가와 재고 추가는 가능하지만 label이 다시 표시 되지는 않습니다. 전체적인 view를 다시 그리는 것이 아니라, 변화가 감지된 해당 view만 update하고 싶으나 아직은 구현하지 못하였습니다. 또한, 전체 뷰를 다시 그리는 방법을 알지 못하여 일부분만 구현된 상태입니다. 

혹시라도, 제가 잘못된 방향으로 진행하고 있다면 저를 막아주세요..🙏

2021-03-08 09:33 UTC, godrm requested changes
미완성이라면 다른 부분을 고치고 있어서 피드백 받고 또 충돌이 날지는 모르겠네요. 
다음 내용을 확인해보고, 일부분만이라도 수정하고 넘어갑시다.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/AppDelegate.swift
> +    let stockCellViews = ViewsUtility.getEachStock(names: ["banana", "chocolate", "stroberry", "coke", "hot6ixRed", "top", "georgia","cantata"])
이게 왜 필요한걸까요?

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/Extension/ArrayExtension.swift
> +    public func toDictionary() -> [ObjectIdentifier:Int] {
이게 모든 배열에서 일반적으로 쓸수 있는 사전형태로 바꾸는 메소드일까요?

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/Extension/StackViewExtension.swift
> +    func addArrangedSubviews(_ views : UIView...){
한꺼번에 추가하는걸 배열이 아니라 가변 변수로 선택한 이유가 있나요?

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/Extension/StringExtension.swift
> +        case "coke" : return Coke.self
윽... 보기에도 확실히 하드코딩한 것은 아쉽네요.
이 함수는 모든 String 타입에 다 공통적으로 필요한걸까요? 
그리고 이런게 왜 필요한지 모르겠습니다.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/Model/Beverage.swift
> +        hasher.combine(ObjectIdentifier(type(of: self)))
만약 이걸로 키로 비교하는 어떤 타입이 있다고 생각해봅시다.
결국 Beverage 하위 타입만으로 구분하는 것인데
타입은 같고, 값이 다른 경우에 Equality가 보장되나요? 일부 속성만 다른 인스턴스가 다 같아져도 되는걸까요?

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/Model/Coffee/CoffeeFactory.swift
>          case is Top.Type : return Top(createdAt: Date().toString(), expiredAt: Date().toString())
생성할 때 String을 써야만 하나요? Date 타입을 그냥 쓰면 안될까요?
이런 경우 value.init()으로는 처리가 안되나요? 
제네릭을 쓴다는 것은 세부 타입을 모르고 쓰려는 건데, swich-case로 구분한다는 것은 타입이 추가될때마다 고쳐야 한다는 얘기가 됩니다. 그만큼 변화에 취약한 타입이고 구조라는 의미입니다.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/Model/FactoryProducer.swift
> +            return nil
이걸 나눌 필요없이 value.init() 형태로 다형성을 활용해보세요.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/Utility/ViewsUtility.swift
> +    }
이 메소드는 응집도가 전혀 없는 메소드고, 타입이네요. OneStockView와 관련이 있다면 거기에 선언해도 되지 않을까요?
그리고 꼭 names를 배열로 넘겨야만 하는 구조인가요? 포커 게임의 Players 와 비슷한 상황아닌가요?

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/View/AddCoinButton.swift
> +        delegate?.addCoin(sender)
UIButton의 Target - Action 은 delegate가 필요없이 이벤트를 보낼 수 있는 구조입니다. 
delegate를 지정하는 대신에 target-action을 지정하면 됩니다.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/View/AddCoinUIButton.swift
> +        configure()
내부 속성은 Int 인데 title은 String 이네요. 이 두 개가 관련있는게 아니던가요?
다른 지정 생성자를 사용했을 때와 `init(frame: CGRect ,named : String)`로 생성했을 때 어떤 차이가 있을까요?
모두가 기본적인 동작을 잘 할까요?

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/View/AddStockButton.swift
> +        self.beverageType = beverageType
특히 초기값을 init() 시점에 넘겨주는 거라면 내부 속성을 private하게 관리하세요.
그건 뷰도 마찬가지입니다.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/View/InspectorStackView.swift
> +        coinButtions.append(AddCoinUIButton(frame: CGRect(x: 0, y: 0, width: bounds.width, height: 10), named: "+5000원"))
버튼 title이나 label.text 값을 생성시점에 결정하는 게 좋지 않을 수도 있습니다.
실행중에 지역이나 언어를 바꾸는 경우도 있을 수 있습니다. 
출력은 매우 유연하게 바꿀 수 있는 구조가 좋습니다.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/View/OneStockView.swift
> +    var imageView : UIImageView!
이름이 너무 직접적으로 타입 이름이네요. 
타입은 다 알고 있으니 역할을 붙여보는 건 어떨까요?

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/View/OneStockView.swift
> +    var beverageType : Beverage.Type!
위에 label, button, imageView 와 다르게 아래 있는 속성들은 뷰가 직접 갖고 있어야 하나 고민해볼 필요가 있습니다.
뷰는 출력하는 데 필요한 값을 갖고 있을 수 있지만, 뷰가 모델이 갖고 있어야 하는 모든 값을 갖는 것은 경계해야 합니다. 
OutputView가 모든 값을 갖고 있어야 하는지 고민했던 것처럼요.
count, image, beverageType이 제대로 할당됐는지, 그 값으로 뷰를 어떻게 표시하는지 로직이 들어가게 되면 테스트하기 어렵습니다.
그래서 요즘은 ViewModel 이라는 OneStockView와 짝을 이루는 출력용 모델을 구현하고, View 대신에 ViewModel을 테스트합니다. 뷰는 ViewModel에 있는 값과 binding해서 포맷 결정이나 로직 구현을 최소화합니다.
여기에 있는 세 가지 속성을 private하게 만들고 테스트할 수 있는지 고민해보세요.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/View/StockHorizontalStackView.swift
> +        self.translatesAutoresizingMaskIntoConstraints = false
사실 요정도는 UIStackView 인스턴스를 만들고 빌더 패턴으로 처리해도 무난한 정도지만 세부 타입으로 구현하는 것도 좋은 시도입니다.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +    }()
StockHorizontalStackView 코드도 이정도면 충분합니다. 더 길어진다 싶으면 MainStackView도 분리해야하나 고민해보세요.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +    lazy var vendingMachine = appDelegate?.vendingMachine
아무리 lazy var로 하더라도 appDelegate?.vendingMachine를 여기에 참조하게되면
appDelegate?.vendingMachine는 소스가 되고, 여기는 참조가 됩니다. 
만약 appDelegate?.vendingMachine 인스턴스가 바뀌면 어떤 일이 생길까요?
여기 속성은 전혀 다른 자판기를 보고 있을 가능성이 높습니다. 따라서 좋은 참조 습관이 아닙니다.

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        }
이 만큼은 StockHorizontalStackView를 만들어서 mainStackView에 추가하는 것 같습니다.
- stockCells에서 뭔가 할 수는 없나요? 
- StockHorizontalStackView을 확장해서 stockCells[] 일부를 넘기면 안되나요?
- mainStackView에서 뭔가 할 수는 없나요?

2021-03-08 09:33 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        }
inspectorView에 coinButtons 여기서 처리해야만 할까요? 
예를 들어 `inspectorView.setTarget(self)` 이렇게 한 번에 요청하면 어떨까요?

2021-03-08 15:14 UTC, ellyheetov commented
JK 리뷰 감사합니다. 고민해보고 수정하여 다시 댓글 달도록 하겠습니다!

2021-03-09 07:44 UTC, ellyheetov commented on VendingMachineApp/Model/Coffee/CoffeeFactory.swift
>          case is Top.Type : return Top(createdAt: Date().toString(), expiredAt: Date().toString())
valu.init()으로 초기화가 가능 한가요??? 

```swift
class Factory : FactoryPattern {
    static func createInstance<T : Beverage>(type value: T)  -> Beverage? {
        return type(of: value).init()
    }
}
```
코드를 수정하여
```swift
let monster = Factory.createInstance(type : Monster.self)
```
인스턴스르 생성하려고 하면, `Static method 'createInstance(type:)' requires that 'Monster.Type' inherit from 'Beverage'` 해당 애러가 발생하는데, value.init() 이 가능한 함수 맞나요...?

2021-03-09 07:52 UTC, godrm commented on VendingMachineApp/Model/Coffee/CoffeeFactory.swift
>          case is Top.Type : return Top(createdAt: Date().toString(), expiredAt: Date().toString())
메타 타입을 쓸꺼면 제네릭으로 쓸 필요가 없지 않나요? 메타 타입과 제네릭을 헷갈리는 것 같습니다.

2021-03-09 07:55 UTC, ellyheetov commented on VendingMachineApp/Model/Coffee/CoffeeFactory.swift
>          case is Top.Type : return Top(createdAt: Date().toString(), expiredAt: Date().toString())
아! 이런🤦🏻‍♀️ 그렇군요. 해당 에러에 너무 꽂혀서 제대로 파악하지 못했네요. 감사합니다.

2021-03-09 08:33 UTC, ellyheetov commented
@godrm JK😃 정말 많이 고민해보았지만, 한번도 적용해 본적이 없는 IBAction collection을 사용하려니 어려워서 질문드립니다. 
기본적으로 sender로 UIButton을 매개변수로 받을 수 있지만, 버튼이 가지고 있는 어떤 정보를 활용 할 수 있는지 잘 모르겠습니다. 
버튼들은 모두 공통의 인터페이스를 사용하고 있지만, 각기 다른 행동을 해야합니다. 이를 위해서는 해당 버튼을 눌렀을때 어떤 타입의 음료를 추가할 것인지에 대한 정보가 필요하게 됩니다.
1. Beverage Type에 대한 정보를 받아 올 수 있는 방법이 어떤게 있나요????
2. Button에 action에 대해서는 delegate를 이용해서 viewController에서 동작하도록 하는게 맞나요? UI만 바꾸는 것이 아니라, 실질적으로 vendingMachine에 음료를 추가해야하니까요.

2021-03-09 08:49 UTC, ellyheetov commented
또한, 위에서 언급한 Beverage.Type을 키 값으로 사용하기 위한 힌트도 부탁드립니다.

2021-03-09 08:58 UTC, ellyheetov commented on VendingMachineApp/Extension/StackViewExtension.swift
> +    func addArrangedSubviews(_ views : UIView...){
아니요. 별다른 이유가 있지는 않습니다. 해당 문법을 처음 봐서 호기심에 사용해 보았습니다...😅

2021-03-09 09:00 UTC, godrm commented
> @godrm JK😃 정말 많이 고민해보았지만, 한번도 적용해 본적이 없는 IBAction collection을 사용하려니 어려워서 질문드립니다.
> 기본적으로 sender로 UIButton을 매개변수로 받을 수 있지만, 버튼이 가지고 있는 어떤 정보를 활용 할 수 있는지 잘 모르겠습니다.
> 버튼들은 모두 공통의 인터페이스를 사용하고 있지만, 각기 다른 행동을 해야합니다. 이를 위해서는 해당 버튼을 눌렀을때 어떤 타입의 음료를 추가할 것인지에 대한 정보가 필요하게 됩니다.
> 
> 1. Beverage Type에 대한 정보를 받아 올 수 있는 방법이 어떤게 있나요????
>    타입에 대한 정보를 미리 가지고 있어야 하는 것 같은데, Button이 Beverage.Type을 가지고 있도록 하는건 어떤가요?
> 2. Button에 action에 대해서는 delegate를 이용해서 viewController에서 동작하도록 하는게 맞나요? UI만 바꾸는 것이 아니라, 실질적으로 vendingMachine에 음료를 추가해야하니까요.

IBAction은 콜랙션보다는 같은 IBAction에 여러 연결을 하기도 합니다.
버튼에다가 저장해놓느냐, 어느 버튼이 어떤 음료와 관련있는지 매칭이 필요할 수도 있습니다. 

UIButton은 target-action 구조가 이미 델리게이트가 필요없이 객체와 메소드를 지정하는 구조입니다. 그래서 델리게이트는 필요가 없습니다.
IBAction이 이미 뷰 컨트롤러를 타겟으로 하는 액션 연결입니다. 코드로 add(target: action:)을 하는 것과 같은거에요.

정리하면 Button이 Beverage.Type을 갖고 있게 할꺼냐, 아니면 어떤 버튼 인스턴스가 보낸 이벤트인지에 따라서 Beverage.Type을 매칭해서 넘길꺼냐 스스로의 기준에 맞춰서 판단하고 결정해보세요. 저에게 허락을 구하는게 아니라 저를 설득하려고 하시면 됩니다. 
개인적으로는 뷰에 모델 정보를 상태값으로 지정해놓는 것을 선호하지는 않고, 매칭 데이터를 갖도록 설계하는 편입니다.
제 이유는 뷰가 구체적인 타입을 알고 있으면 그 뷰는 유연하지 않고 커플링이 되기 때문에 재사용성도 떨어집니다. Beverage.Type에 대한 추상타입에 의존하도록 만들수 있다면 가능하다고 생각합니다.

2021-03-09 11:30 UTC, closed without merging