[Min] Step3 metaType을 이용하여 Factory Method 수정 & 자판기 UI 구현
code-squad/swift-vendingmachineapp pull request #279
Opened 2021-03-08 08:25 UTC by youngminshim-de

- metaType을 활영하여 Factory Method 수정 [ ] 

- 스토리보드에 자판기 UI구현 ( Button, Image, label을 포함하는 Beverage Stack View 생성) [ ] 

- IBOutlet Collection을 이용하여 여러 중복되는 IBOutlet 제거[ ] 

- UIImageView CornerRadius 이용하여 코너 변경[ ] 

- View Controller 에서 button, label, imageView OutletCollection 파일 -> View 폴더로 분리 [ ] 

## 학습내용

* metaType, IBOutlet Collection, View

## 고민과해결

* 스택뷰 안에 imageView를 넣었음에도, image의 size가 달라 원하는 대로 UI가 나오지 않아 image size를 모두 동일하게 바꿔준 뒤 asset에 추가하여 사용했는데 이같은 방법으로 해도 되는건지 궁금합니다..
*  다른분들 pr을 보고 힌트를 얻어 button, label, beverage를 dictionary type으로 사용해서 구현하긴 했는데, 이 같은 방법이 맞는지 모르겠습니다.. 검색을 해도 뚜렷한 해결책을 못찾아서 혹시 다른방법이 있다면 알려주시면 감사하겠습니다ㅠ

2021-03-08 09:49 UTC, godrm requested changes
수고하셨습니다. 하드 코딩된 것들과 팩토리에서 타입을 구분하고 있는 부분만이라도 개선하고 넘어가보죠.

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage/Beverage.swift
> +        return money.money >= price
Money 타입을 만들었으면 `money.compare(with: price)` 형태가 좋습니다.
money.money는 이상하지 않나요?

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Beverage/Coffee/CoffeeFactory.swift
> +            return Georgia(manufacturer: manufacturer, volume: volume, price: price, brand: brand, manufactured: manufactured, expiry: expiry, calorie: calorie, temperature: temperature, caffeineCont
이런 타입을 비교하거나 지정하지 않고 다형성으로 ofType.init() 형태가 되도록 해보세요.

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +}
이 에러는 무엇에 대한 에러일까요?
InventoryError 보다 Inventory.Error가 더 읽기 편하고 네임스페이스가 있어서 관리하기 좋습니다. 
그리고 import 보다 위에 선언하는 것은 보기 좋지는 않습니다.

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
>      func subtractBeverage(beverage: Beverage) -> Beverage? {
이 함수는 이상하지 않은가요? 함수 이름을 `subtractBeverage(beverage: Beverage)` 에서 매개변수까지라고 생각하세요. subtract(beverage:)가 되도 충분하다는 말입니다.
특정한 음료수를 빼는데, beverage 인스턴스를 지정해서 딱 그 음료수 인스턴스 빼는건가요? 아니면 그 음료수과 같은 타입의 다른 인스턴스를 빼는건가요? 만약 전자라면 리턴타입이 없어도 되는거 아닌가요? 같은거니까요

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +            print(error)
catch에서 에러는 print하는 것은 앱 개발에 별 도움이 안됩니다.
차라리 아래처럼 return nil을 그대로 쓰는 게 낫습니다.

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +            throw InventoryError.empty
Inventory가 비어있는 상태가 앱에서 얼마나 중요한 에러일까요?
에러 타입은 앱을 정상적으로 사용할 수 없는 경우에 쓰는 거라고 생각하세요.
음료가 없으면 그냥 return 0 하는 것과 뭐가 다른가요? 

그리고 search 결과가 음료 개수를 리턴하는 건가요? 아니면 index를 넘기는 건가요?
searchBeverage 동작이 구체적으로 무엇을 하려는 것인지 유추하기 어렵네요.

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +                                 ofType: Georgia.self)!
인스턴스를 생성하는 것은 어느정도 하드코딩이 필요하지만 이렇게 팩토리까지도 타입별로 있어야 한다면 이건 유연하지 않은 구조입니다. 
음료 타입을 활용해서 일반화시켜보세요.

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/View/AddBeverageButton.swift
> +        self.setTitle("추가", for: .normal)
setButton()은 동작이 정확하지 않습니다. 
AddBeverageButton.setButton()은 무엇을 하는 것인지 유추가 안되네요. 버튼에 버튼을 넣는건가요?
단지 타이틀을 바꾸는 거라면 서브 클래스를 만들지 않아도 빌더패턴으로 인스턴스 만들고 title을 지정하면 됩니다. 그 사이 기준을 정해보세요.

2021-03-08 09:49 UTC, godrm commented on VendingMachineapp/VendingMachineapp/ViewController.swift
> +        vendingMachine.increaseMoney(money: 5000)
Money 타입이 있는데 여기 넘기는 값은 Int 네요. 카드 게임에서처럼 타입을 선언했으면 그 타입을 그대로 활용하려고 노력해보세요.

2021-03-09 02:08 UTC, youngminshim-de commented on VendingMachineapp/VendingMachineapp/ViewController.swift
> +        vendingMachine.increaseMoney(money: 5000)
Money Type을 직접사용하려다 보니 Money(with: -Beverage.price) ) , Money(with: 1000) 등과 같이 매개변수로 전달해주었는데.. 이같은 방식이 맞는건지 잘 모르겠습니다.. 맞다고 하면 어떤 필요성이 있는지 잘 모르겠습니다. 단지 Money Type을 만들어주었기에 사용하기 위함? 인것인가요??

2021-03-09 02:29 UTC, youngminshim-de commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +            print(error)
Exception Handling 에 대해 공부하는 겸 시도해봤는데, 너무 억지로 집어넣은 것 같습니다.
어떠한 error 처리를 해주고 싶은데, 마땅히 어떤걸 해줘야 할지 몰라 print(error)를.. 피드백 참고하겠습니다!

2021-03-09 03:10 UTC, youngminshim-de commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +            throw InventoryError.empty
search의 결과는 index를 넘기는 함수입니다. 하지만 return으로 0을 해줬을 경우 inventory[0] 이 삭제되어 코드를 이와같이 구현했습니다. (inventory에는 같은 타입의 인스턴스가 여러개 있기 때문에, 해당 beverage type의 인스턴스가 없다하더라도 inventory가 비어있다고는 볼 수 없기 때문에..)

2021-03-09 03:40 UTC, godrm commented on VendingMachineapp/VendingMachineapp/ViewController.swift
> +        vendingMachine.increaseMoney(money: 5000)
의도적인 연습을 하는 거죠. Money가 별 기능이 없다고 생각되지만, 세부적인 동작을 하는 타입을 선언하고 사용하는 것은 OOP 설계와 구현을 연습하는 데 매우 중요한 포인트입니다. 
포괄적인 Int, Array, String 보다는 그 값들을 포함하는 타입을 설계하고, 활용하는 방식을 연습해야만 적절한 하위 타입을 설계하고 구현할 수 있게 됩니다. 그렇지 않으면 프로그램 구조가 약해집니다. 한 번 만들고 버리는 프로그램이라면 뭘써도 누가 만들어도 괜찮을 겁니다. 
하지만 한 달만 지나도 (혹은 다른 개발자가 읽을 때도) Int 가 Money 라는 개념과 동일하구나. 하는 것을 기억하기 어렵습니다. 
그 의미를 명확하게 해주고, 그 타입을 활용하는 구조를 만들어놓으면 다시 읽어도 1분 이내로 그 역할을 이해할 수 있습니다. 그래서 연습하는 겁니다. 여전히 납득이 되지 않는다면 넘어가도 됩니다. 대신 본인도 납득하기 어려운 것은 다른 개발자를 설득하기는 어렵다고 생각하면 됩니다.

2021-03-09 03:42 UTC, godrm commented on VendingMachineapp/VendingMachineapp/Model/Inventory.swift
> +            throw InventoryError.empty
그런 맥락에서 Index라는 것도 타입이 필요한 것은 아닌가 고려해보세요. Int로 Index를 표현하려니까 그런 예외적인 상황이 생기는 게 아닐까요? 혹은 Result<> 타입에 대해서도 살펴보세요. 성공/실패를 한꺼번에 넘기는 방법도 가능합니다.

2021-03-09 11:56 UTC, youngminshim-de commented on VendingMachineapp/VendingMachineapp/View/AddBeverageButton.swift
> +        self.setTitle("추가", for: .normal)
<pre>
protocol Builder {
    associatedtype item
    var product: item {get}
    func setText(name: String) -> Self
}

class ConcreteBuilderButton: Builder {
    var product = UIButton()
    
    func setText(name: String) -> Self {
        self.product.setTitle(name, for: .normal)
        self.product.setTitleColor(.blue, for: .normal)
        return self
    }
}

class ConcreteBuilderLabel: Builder {
    var product = UILabel()
    
    func setText(name: String) -> Self {
        self.product.text = "0"
        return self
    }
}

class Director {
    static func makeProduct<T: Builder>(builder: T) -> T.item{
        let build = builder
        build.setText(name: "추가")
        return build.product
    }
}
</pre>
빌더패턴을 적용해보려고 이런식으로 따로 swift 파일을 만들어서 했더니 적용이 되지 않더라구요..
제가 생각한 원인으로는 이미 스토리보드로 만들어져있는 button에 새로운 UIButton() 파일을 넣어줘서 연결이 되지 않는 것 같은데
제가 생각한게 맞는지 모르겠습니다..

2021-03-09 12:03 UTC, youngminshim-de commented
수정사항
1. 팩토리메소드 수정
2. Int Type -> Money Type 으로 매개변수 전달하도록 함수 수정

추가 공부할 내용
1. 빌더패턴
2. Result<> 타입

너무 중구난방으로 정리가 되지 않는 느낌이 많이 들어 현재까지 진행상황을 일단 push 하겠습니다.
조금 정리가 되고 나머지 추가적인 사항 수정해보려고 합니다

2021-03-10 02:18 UTC, godrm commented on VendingMachineapp/VendingMachineapp/View/Builder.swift
> +import Foundation
UIKit을 import 하는 경우는 따로 Foundation을 쓰지 않아도 포함됩니다.

2021-03-10 02:23 UTC, godrm commented on VendingMachineapp/VendingMachineapp/View/Builder.swift
> +}
일반화한 빌더를 만드는 건 재밌는 시도네요. 나쁘지 않습니다.
사실 UIButton 타입 자체가 이미 빌더 패턴이 들어있는 형식이기도 합니다. 
어떤 init을 하느냐에 따라 조금씩 다른 버튼 인스턴스가 생성되거든요. 참고하세요.

2021-03-10 02:24 UTC, godrm commented on VendingMachineapp/VendingMachineapp/ViewController.swift
> +            beverageButtons[index].setTitle("추가", for: .normal)
빌더로 한꺼번에 만들꺼면 이런 내용이 없어야 합니다. 
여기서도 처리하고 있다는 것은 어느 하나가 제 역할을 못하는 것은 아닐까요?

2021-03-10 02:25 UTC, merged