Ray step6
code-squad/swift-vendingmachineapp pull request #305
Opened 2021-03-12 06:51 UTC by torch-ray

## Step6 작업목록
- [x] 구매목록 구현 완료
- [x] 구매목록에 사진 우측하단에 나타내기 구현 완료
- [x] UIScrollView 적용하여 가로로 스크롤하여 구매 목록 확인가능
- [x] 실행화면 추가

## 학습키워드
- UIScrollView
- 스토리보드 vs Nib vs 코드

## 고민과 해결
- UIScrollView 구현에 시간이 오래 걸림
- 이미지를 추가함에 따라 어느시점부터 스크롤이 작동하지 않음
- 처음에는 ScrollView의 widthAnchor를 조절하기 위해 코드 수정하였으나 실패
- 시행착오 끝에 contentSize.width를 조절해야 작동하는 것을 파악하고 수정

## 부연설명

- UIScrollView구현 위주로 코딩하였습니다.
- 구매목록을 확인하는 NotificationCenter를 추가하였습니다.

## 질문거리
- 코드로 뷰를 생성해서 추가하는 것과 스토리보드 상에서 미리 생성하는 것의 차이점을 학습하기 위해 코드와 스토리보드간 장단점을 찾아봤습니다. 명시적으로 둘 사이의 차이점을 언급한 글은 없었지만, 추측하건대 코드로 뷰를 생성하면 메모리 오버헤드를 막을 수 있고 스토리보드는 실행과 동시에(사용여부와 관련없이) 메모리에 올라가다 보니 오버헤드가 발생할 수 있다는 것 같습니다. 질문에 대해 적절한 방향으로 학습 중인지(?) 궁금합니다!! ㅎㅎ

2021-03-12 07:33 UTC, godrm requested changes
다음 내용들을 확인해보세요. 조금 더 생각해볼 여지가 있습니다.

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +        NotificationCenter.default.post(name: .updateBeverages, object: nil, userInfo: nil)
object가 sender 역할이라서 정확하게 표현할 때는 필요할 수도 있습니다. self를 지정해주는 게 좋습니다.

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
>          insertedMoney = coder.decodeObject(forKey: "insertedMoney") as! InsertedMoney
싱글톤 자판기를 구현하면 어떤 점이 안좋을까요?
로딩할 때 인스턴스가 바뀌어야 한다면, 로딩관련 내용이 외부에 있는게 좋을까요? 내부에 있는게 좋을까요?

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +        NotificationCenter.default.post(name: .updateInsertedMoney, object: nil, userInfo: nil)
관련 Notification.Name은 어디에 선언되어 있나요? 자판기에서 발생하는 이벤트라면 자판기 내부에 선언하는 게 어떨까요?

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            NotificationCenter.default.post(name: .updatePurchased, object: nil, userInfo: nil)
지금 음료수를 구매를 하면 해당하는 이벤트가 각각 발행합니다. 이게 좋을까요? 아니면 하나만 보내도 될까요?

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +    private var vendingMachine = VendingMachine.sharedInstance()
싱글톤으로 사용하는 경우에 이렇게 변수에 선언하면
싱글톤이 다시 바뀌더라도 vendingMachine 변수는 이전 인스턴스를 가르키게 됩니다.
그래서 싱글톤일 때는 차라리 그냥 VendingMachine.sharedInstance()를 참조하는 게 엉뚱한 인스턴스를 참조하는 것보다 더 낫습니다. 
하지만 싱글톤은 구체 타입에 그대로 의존하게 됩니다. 여기 뷰 컨트롤러는 자판기와 강한 결합이 되서 분리가 힘들어집니다.
싱글톤으로 구현하더라도 인터페이스(프로토콜)에 의존하도록 만들수 있을까요?

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +    private var imageView = UIImageView()
타입 이름과 똑같은 뷰 이름이라 정보가 부족합니다. 어떤 역할을 하는 뷰일까요? 
변수 이름에 타입 이름은 제외하고 역할을 표현하는 게 좋습니다.

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
>          view.backgroundColor = UIColor.systemGray5
이런 값은 인터페이스 빌더에서 바꿔도 될 것 같은데, 딱 배경색만 코드로 지정한 이유가 있나요?

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        for idx in 0..<buyingList.count {
- idx처럼 줄여서 쓰는 변수는 지양하세요.
- purchaedBeverageList()는 기존 뷰를 매번 지우고, 새로운 뷰를 매번 다시 그리는 걸까요?
이게 좋은가요? 새로 구매한 경우만 추가하는 게 낫지 않을까요?

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +    }
뷰를 선언하고 초기화 하는 코드가 길어지면 뷰를 분리하고 재사용하는 것을 고민해 봐야 합니다.
뷰도 하위 타입을 만들어서 코드를 옮기는거죠. 그러면 뷰 컨트롤러가 좀 더 단순해질 겁니다.

2021-03-12 07:33 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: ChocolateMilk())
저는 이게 조금 의아한데요. 자판기에서 음료수를 구매하는 데 꼭 해당 음료수 인스턴스가 있어야 하나요?
그냥 ChocolateMilk.Self를 넘기면 안되는 건가요? 구매 결과는 인스턴스가 맞겠지만 구매할 때도 필요한지 모르겠습니다.

2021-03-12 08:36 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
>          insertedMoney = coder.decodeObject(forKey: "insertedMoney") as! InsertedMoney
로딩관련 내용이 외부에 있다고 하면, 자판기 객체 외부를 말씀하시는건가요? ㅠㅠ

2021-03-12 08:37 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            NotificationCenter.default.post(name: .updatePurchased, object: nil, userInfo: nil)
가능하면 NotificationCenter는 줄이려고 노력했는데, 해당 메서드의 경우 세가지 프로퍼티에 모두 영향을 미친다고 생각했는데... 만약 하나만 보내도록 바꾸려면 메서드의 기능을 분리해야할까요? 아니면 현재 메서드에서 이벤트를 하나만 보낼 수도 있을까요?

2021-03-12 08:39 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        for idx in 0..<buyingList.count {
넵 ㅠㅠ 저도 안좋은거 같은데.. 수정을 한다고 생각하면 purchased라는 프로퍼티는 아예 필요 없을 거 같긴합니다. 구매전체 목록을 굳이 확인할 필요는 없으니까..? 그런데, 만약 그렇게한다면 버튼을 눌렀을 때 vendingmachine의 프로퍼티를 2개를 호출할 것 같은데 버튼 하나가 여러개의 프로퍼티를 호출하게 하는 방식은 괜찮을까요?

2021-03-12 08:45 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
>          insertedMoney = coder.decodeObject(forKey: "insertedMoney") as! InsertedMoney
네. 여기가 VendingMachine 클래스니까 자판기 외부를 의미하는 거죠

2021-03-12 08:45 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            NotificationCenter.default.post(name: .updatePurchased, object: nil, userInfo: nil)
그걸 고민해보세요. 정답이 하나만 있는게 아닙니다.

2021-03-12 08:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        for idx in 0..<buyingList.count {
그럴수도 있죠. 버튼을 누를때마다 추가되도록 해도 되겠죠. 꼭 모든것을 배열로 전달해야 한다는 의미는 아닙니다. 더 좋은 방법이 있으면 그걸 선택해도 됩니다.

2021-03-12 10:35 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: ChocolateMilk())
타입으로 넘기려고 해봤는데.. buyBeverage의 파라미터로 메타타입을 넘기면 buyBeverage안에서 작동해야하는 메서드들이 인스턴스 멤버에 접근을 못하는데.. 혹시 이것과 관련해서 해결할 수 있는 힌트를 조금 주실 수 있을까요?

2021-03-15 05:36 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: ChocolateMilk())
buyBeverage() 내부에서 인스턴스 속성에 접근을 못한다구요? buyBeverage가 static으로 선언한 타입 메소드인가요?
아니면 Beverage 인스턴스의 속성에 접근해야 한다는 의미인가요?

2021-03-15 05:41 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: ChocolateMilk())
Beverage 인스턴스의 속성에 접근을 해야하도록 로직이 이뤄져있습니다! buyBeverage 메소드가 파라미터로 메타타입을 받도록 수정하면 인스턴스의 속성에 접근을 못하게되서... 질문을 드렸습니다!

2021-03-15 05:45 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: ChocolateMilk())
그 속성이 뭔가요? price일까요? 
그렇다면 price는 음료수 제품 분류(class)마다 구분되는 값일까요. 인스턴스마다 구분되는 값일까요
이렇게 꼬리를 물고 생각해봐야 합니다.  

결국 구매하는 데 인스턴스가 필요한데, 음료수 가격 때문이군요.
그러면 그 음료 타입의 인스턴스를 하나 먼저 결정하고, 그 인스턴스 가격과 보유 금액을 비교하면 되지 않을까요?

2021-03-15 05:48 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: ChocolateMilk())
피드백 주셔서 감사합니다! 세부 구현 방법은 조금 더 생각해봐야겠지만, 피드백 주신 내용 바탕으로 수정시도해보겠습니다!

2021-03-15 06:25 UTC, godrm commented
이 상태로 머지하고 다음 단계에서 할 껀가요? 열어놓고 PUSH할껀가요?

2021-03-15 07:57 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +        NotificationCenter.default.post(name: .updateBeverages, object: nil, userInfo: nil)
수정하였습니다!

2021-03-15 07:58 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
>          insertedMoney = coder.decodeObject(forKey: "insertedMoney") as! InsertedMoney
이 부분은 추가 학습하였으나, 아직 의도하신 수정 방향을 이해하지 못했습니다...

2021-03-15 07:59 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +        NotificationCenter.default.post(name: .updateInsertedMoney, object: nil, userInfo: nil)
내부에 선언하였는데, 이렇게되니 해당 클래스 외에서 접근할 때는 VendingMachine.sharedInstance().으로 접근하긴 해야하는데 괜찮은 방법일까요?

2021-03-15 07:59 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +        NotificationCenter.default.post(name: .updateInsertedMoney, object: nil, userInfo: nil)
인스턴스마다 구분될 필요는 없는 값이니까 static으로 하면 어때요?

2021-03-15 07:59 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/VendingMachine.swift
> +            NotificationCenter.default.post(name: .updatePurchased, object: nil, userInfo: nil)
메서드를 나누는 것도 좋은 방법이나(이는 언제든 적용할 수 있어서), NotificationCenter를 나누는 쪽으로 수정해봤습니다.

2021-03-15 08:00 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +    private var vendingMachine = VendingMachine.sharedInstance()
프로토콜로 시도하려고 했으나 그렇게 되면 vendingMachine의 타입이 SingletonProtocol(싱글톤을 위해 만든 프로토콜의 이름)과 같이 되는거 같은데 그렇게 되면 VendingMachine의 메서드에 접근이 어렵습니다... 힌트를 조금 주실 수 있을까요?

2021-03-15 08:00 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +    private var imageView = UIImageView()
수정했습니다!

2021-03-15 08:00 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updatePurchased(notification:)), name: vendingMachine.updatePurchased, object: nil)
옵저버를 등록할 때도 object를 sender 의미로 지정하는 게 더 좋습니다. 참고하세요.

2021-03-15 08:01 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
>          view.backgroundColor = UIColor.systemGray5
이 부분은 인터페이스빌더  vs nib vs 코드 를 학습하면서 인터페이스 빌더에서 바꾸는게 좋다고 판단하여 수정하였습니다!

2021-03-15 08:01 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        for idx in 0..<buyingList.count {
새로 구매한 경우만 추가하도록 수정하였습니다!

2021-03-15 08:02 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +    }
스택뷰라는 클래스를 생성하여 코드를 옮겨봤는데 막상 뷰컨트롤러에서 옮겨올 수 있는 코드가 별로 없는 것 같습니다. 혹시 이런 수정 방향이 맞을까요...?

2021-03-15 08:02 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: ChocolateMilk())
이 부분은 결국 구현하지 못했습니다. 음료의 타입으로 인스턴스를 하나 먼저 결정한다는 부분을 이해하지 못했습니다 ㅠㅠ

2021-03-15 08:04 UTC, torch-ray commented
수정하긴했으나, 싱글톤을 프로토콜로 구현 부분과 메타타입에서 인스턴스 프로퍼티로의 접근을 수정하지 못했습니다... 혹시 조금 더 접근할 수 있는 방식에 대해 힌트를 주실 수 있을까요?

2021-03-15 08:07 UTC, torch-ray commented
> 이 상태로 머지하고 다음 단계에서 할 껀가요? 열어놓고 PUSH할껀가요?

Push했습니다ㅎㅎ 가능하실때 리뷰 뷰탁드립니다 ㅠㅠ

2021-03-15 08:13 UTC, godrm commented
> 수정하긴했으나, 싱글톤을 프로토콜로 구현 부분과 메타타입에서 인스턴스 프로퍼티로의 접근을 수정하지 못했습니다... 혹시 조금 더 접근할 수 있는 방식에 대해 힌트를 주실 수 있을까요?

관련된 코드에 코멘트를 남기면 더 정확하게 얘기할 수 있을 겁니다. 
싱글톤으로 만드는 것은 그냥 인스턴스가 하나냐 여러 개냐 이런 차이만 있을 뿐입니다. 프로토콜을 채택하고 그걸 전달하는 것은 싱글톤이든 아니든 어떤 타입이든 동일하죠.

---

메타 타입에서 인스턴스 프로퍼티를 접근하는 것이 필요한가요? 그건 이상한데요?
메타 클래스는 클래스 자체를 값으로 쓰기 위한것이지, 인스턴스에 속성에 접근하려는 게 아닙니다. 
클래스 타입 값과 인스턴스를 사용해야 하는 경우가 혼동된다는 의미일까요?

2021-03-15 08:14 UTC, merged

2021-03-15 08:39 UTC, torch-ray commented
addBeverage(버튼을 눌렀을 때 재고를 추가하는 메서드)와 같은 메서드에 파라미터 값으로 메타타입을 넘기는 것에 대해 고민 중인데, 메타타입이 파라미터로 넘어오면 addBeverage메서드 내부 로직에서 파라미터로 인스턴스 프로퍼티(price)에 접근할 수가 없어서 수정 방식을 못찾았습니다! 이전 리뷰 주신게 '결국 구매하는 데 인스턴스가 필요한데, 음료수 가격 때문이군요.
그러면 그 음료 타입의 인스턴스를 하나 먼저 결정하고, 그 인스턴스 가격과 보유 금액을 비교하면 되지 않을까요?' 였는데 '음료 타입의 인스턴스를 하나 먼저 결정하고' 부분에 대해 고민하고 학습했는데 어떤 의미인지 이해하지 못했습니다 ㅠㅠ

2021-03-15 08:49 UTC, godrm commented
> 그러면 그 음료 타입의 인스턴스를 하나 먼저 결정하고, 그 인스턴스 가격과 보유 금액을 비교하면 되지 않을까요?' 였는데 '음료 타입의 인스턴스를 하나 먼저 결정하고' 부분에 대해 고민하고 학습했는데 어떤 의미인지 이해하지 못했습니다 ㅠㅠ

타입이 매개변수로 넘어갔으니까... 그 타입과 같은 인스턴스를 찾을 수 있지 않을까요? 
음료를 추가할 때는 인스턴스로 재고를 추가하는 게 맞겠죠. 콜라 제품이 5개 있어야 5개를 판매할 수 있는거니까요.
그런데 구매할 때는 `콜라 제품 중에 하나`를 구매하는 거지, 콜라 제품을 가져와서 동일한 제품을 구매하는 건 아니니까요 (이게 설명하기 어렵네요 ㅎㅎ)
다시 설명하면 입력이 제품 타입이고 그 중에 인스턴스 하나를 고르는 게 구매 과정에서 일어나는 일이라는 겁니다.
미리 인스턴스를 정해서 인스턴스와 같은 것을 결정하는 게 아니라는거죠.

2021-03-15 09:03 UTC, torch-ray commented
아... 이해했습니다! 감사합니다! 다음스텝 시작전에 필요한 부분은 수정하고 넘어가겠습니다!