[Elly] Step4, Step5 - 아카이빙, NotificationCenter
code-squad/swift-vendingmachineapp pull request #306
Opened 2021-03-12 07:23 UTC by ellyheetov

하다보니 Step5까지 진행되어 한번에 리뷰 부탁드립니다!

# 프로그래밍 요구사항
- [x] VendingMachine 변수를 ViewController에서 포함하지 않고 AppDelegate로 옮긴다.
- [x] 앱 종료(background) 시점 콜백 함수에서 VendingMachine 객체 인스턴스 속성을 저장한다.
- [x] 저장할 때는 VendingMachine을 아카이브해서 하나의 데이터 값으로 변형한다.
- [x] 값을 저장하고 복원하는 데에는 UserDefault 라는 파운데이션 라이브러리를 사용한다.
- [x] 앱 시작(activate) 시점 콜백 함수에서 기존에 저장된 값에서 불러와서 VendingMachine 객체 인스턴스를 생성한다.
- [x] 복원할 때는 저장된 데이터 값을 언아카이브해서 VendingMachine 객체를 생성한다.
- [x] ViewController는 viewDidLoad에서 Observe를 등록한다.
- [x] 음식 재고가 바뀌는 Notification을 받으면 화면에 Label을 업데이트한다.
- [x] VendingMachine 모델 객체에서는 변화에 대해 NotificationCenter에 post한다.
- [x] 모든 동작은 이전 단계와 동일하게 동작해야 한다.

# 학습 키워드
- NSCoding, Codable, Archiving, MVC, App의 생명주기

# 고민과 해결
- README.md를 봐주세요.

# 질문
- button의 setTitle이 동작하지 않습니다. 전혀 이유를 모르겠습니다.

2021-03-12 07:34 UTC, godrm commented
setTitle() 매개변수가 2개인 걸 써보세요. 뒤에 .normal 같은 상태가 들어간 걸 써야 합니다.

2021-03-12 07:36 UTC, ellyheetov commented on VendingMachineApp/View/OneStockView.swift
> -        button.setTitle("추가하기", for: .normal)
이부분에서 setTitle이 동작하지 않습니다. 왜그런 걸까요...?

2021-03-12 08:00 UTC, godrm requested changes
수고하셨습니다. 다음 내용들을 확인해보세요.
특히 NotificationCenter 부분은 수정하고 넘어가죠

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/AppDelegate.swift
>          return true
AppDelegate, SceneDelegate, ViewController, VendingMachine 객체가 생성되는 시점과  
willFinish... didFinish, willConnect, viewDidLoad 등 초기에 불리는 메소드들 호출되는 시점을 순서대로 비교해보세요.  
그래야 객체가 어떤게 먼저 생기고, 어떤 메소드가 호출되는지에 따라서 참조 관계가 명확해집니다.  
그렇지 않으면 자판기 객체가 여러번 생길 수도 있고, 인스턴스가 달라졌는데 서로 다른 것을 참조하기도 합니다.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Extension/NotificationExtension.swift
> +}
이 노티는 누가 보내고 누가 받는 걸까요? 별도 파일로 있는 것과 관련있는 타입 내부에 nested 된 것과 어떤 차이가 있을까요?

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/Beverage.swift
> +    }
이름과 타입이 같으면 같은 인스턴스일까요? 용량은요? 가격은요? 상관없는건가요?

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/Beverage.swift
>          self.expiredAt = Date().get7daysLatter()
상속 관계에서는 이런 required init은 어쩔수 없이 선언해야 하는데 이 부분이 아쉬운 부분이죠.
의미없는 초기값을 지정해줘야 하니까요.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/Beverage.swift
>          return expiredAt.isExpired()
이 메소드는 어떻게 테스트할 수 있을까요? 매일매일 테스트하는 게 다를 수 있을까요? 
그래서 값을 활용하지 않더라도 매개변수를 넘겨주는 순수 함수로 만들어서 테스트 가능하도록 만드는 게 좋습니다.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/Coffee/Cantata.swift
> +        self.kind = Kind(rawValue: coder.decodeObject(forKey: "Cantatakind") as! String)!
이런 구조에서도 강제 언래핑은 좋지 않습니다. 아카이빙한 값이 깨질 수도 있고 키값이 바뀔수도 있고 어떤 상황에서도 강제 언래핑 보다는 예외적인 처리를 해놓는 게 좋습니다.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/Coffee/Coffee.swift
> +        return Coffee.standard <= temperature
제 피드백은 매개변수로 기준값을 넘기자는 겁니다. 그래야 메소드가 어떤 값을 넣느냐에 따라 테스트 가능한게 됩니다.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/DataManager.swift
> +        } catch {
지금처럼 자판기 자체를 저장하는 것과 달리
자판기 인스턴스는 그대로 두고, 꼭 내부 데이터만 저장했다가 로딩하는 것은 어떨까요? 어떤 차이가 있을까요?

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/Money.swift
>      private(set) var coins : Int
Money라는 타입을 선언해서 최대한 활용해보려는 데는 Int 타입을 접근하지 못하게 하고 Money 타입으로 거의 모든 부분을 표현할 수 있으냐 입니다. 그 부분이 조금 아쉽네요.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/Money.swift
>      public func add(with coin : Int){
같은 맥락에서 coin을 넣을 때도 Int로 넣는게 아니라 Money를 넣는다고 볼 수 있죠

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
> +        return dict[ObjectIdentifier(type)]?.first
5단계를 했다고 써있는데, Notification Post하는 코드가 없는데요?

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/View/StockStackView.swift
>          }
여기 두 메소드가 있는데 차이점을 잘 모르겠습니다. 매개변수 구조가 같은데 같은 역할을 하는건가요? 다른 역할을 하는건가요?

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/View/UIBeverageButton.swift
> +        setUpButton()
UIBeverageButton을 만드는 것은 좋은 시도입니다만
구체적인 하위 타입을 갖고 있는게 정말 좋은가는 고민해봐야 합니다.
이 정도면 타입이 추가되거나 사라져도 변화가 생겨도 큰 무리없이 동작할 것 같네요.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/View/UIBeverageButton.swift
> +        self.addTarget(superview, action: #selector(ViewController.appendBeverageToMachine), for: .touchDown)
타깃 엑션을 여기서 지정하는 것은 `ViewController.appendBeverageToMachine`를 직접적으로 알고 있는 거라서 강한 결합이 됩니다.
버튼 설정은 내부에서 하고, 연결은 외부에서 하는 것도 괜찮습니다.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/View/UICoinButton.swift
> +        self.setTitle(title, for: .normal)
꼭 생성 시점에 title이 중요한가요?
하위 모델의 값이 계속 바뀌어야 한다면, 뷰가 생성될 때 초기 값을 넘겨주는 게 큰 의미가 없습니다.
하위 모델이 값이 바뀔 때마다 연결해서 계속 뷰를 다시 그리게 되는 구조가 더 낫습니다.

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        NotificationCenter.default.post(name: .StockCountChanged, object: nil)
옵저버 구조에 대해 다시 생각해보세요.
post 하는 객체와 observer 하는 객체는 서로 다른 객체여야 합니다. 
같은 객체라면 그냥 호출해도 되는거죠

2021-03-12 08:00 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateCoinLabel), name: .CoinChanged, object: nil)
옵저버 등록할 때 마지막 object는 sender의 의미입니다. 어떤 객체가 post를 하는지도 고려해보세요.

2021-03-12 08:00 UTC, godrm commented on VendingMachineAppTests/VendingMachineAppTests.swift
> +        expectDict.removeValue(forKey: ObjectIdentifier(Georgia.Type.self))
테스트 코드는 작게 테스트 함수 하나가 하나를 테스트하는 게 좋습니다.
여기있는 테스트들이 통과하는 게 목적이 아니라, 테스트가 실패했을 때 테스트 함수 이름만 보고 어느 코드의 동작이 안되는 것인지 바로 파악할 수 있어야 합니다. 
지금처럼 작성하면 이 중에 어디에서 실패했는지 테스트 코드를 살펴봐야 하는데 그런 것을 기대하는 게 아닙니다.

2021-03-12 10:42 UTC, ellyheetov commented on VendingMachineApp/AppDelegate.swift
>          return true
현재 코드에서는 
1. AppDelegate에서 willFinishLaunchingWithOptions →  didFinishLaunchingWithOptions 가 수행되고
2. VendingMachine의 객체가 초기화 된 후
3. ViewContr oller의 viewDidLoad → viewWillAppear가 차례대로 수행됩니다. 

이와 같은 결과로 미뤄보아 AppDelegate에 willFinishLaunchingWithOptions 메소드 안에서 VendingMachine를 생성하면 될 것 같습니다. 혹시 제가 놓치고 있는 부분이 있을까요???

2021-03-12 10:43 UTC, ellyheetov commented on VendingMachineApp/Extension/NotificationExtension.swift
> +}
VendingMachine에 상태에 대한 Notification이므로, VendingMachine 타입 내부에 nested 된 것이 더 좋을 것 같네요. 수정하겠습니다.

2021-03-12 10:43 UTC, ellyheetov commented on VendingMachineApp/Model/Beverage.swift
> +    }
미쳐 생각하지 못했네요. 브랜드, 용량, 가격, 이름이 모두 같아야 같은 인스턴스가 되도록 하였습니다.

2021-03-12 10:43 UTC, ellyheetov commented on VendingMachineApp/Model/Beverage.swift
>          return expiredAt.isExpired()
수정한다면서 놓친 부분이 있었네요. 다시 말씀해주셔서 감사합니다. 수정했습니다.

2021-03-12 10:43 UTC, ellyheetov commented on VendingMachineApp/Model/Coffee/Cantata.swift
> +        self.kind = Kind(rawValue: coder.decodeObject(forKey: "Cantatakind") as! String)!
코드를 작성하면서 고민했던 부분 중 하나 였습니다.  코드가 지저분해지는 것 같아서 강제 언래핑을 하게 되었습니다. `guard let` 을 사용하는 것이 더 나은 선택 이었을까요? 앱이 죽어 버릴 수 있으니까요.

2021-03-12 10:43 UTC, ellyheetov commented on VendingMachineApp/Model/Coffee/Coffee.swift
> +        return Coffee.standard <= temperature
완전히 반대로 생각해 버렸네요.ㅎㅎ 수정하도록 하겠습니다.

2021-03-12 10:43 UTC, ellyheetov commented on VendingMachineApp/Model/DataManager.swift
> +        } catch {
사실 자판기 자체를 저장하는 것이 아니라, 자판기가 가지고 있는 Beverage 배열을 저장 했다가 로딩하려고 했었습니다. 하지만, 요구사항을 최대한 따르기 위해서 VendingMachine을 저장하게 되었습니다. VendingMachine은 여러가지 객체를 담고있는 객체로써 인코딩/디코딩 시에 더 많은 오버헤드가 발생하지 않을까 하는 추측이 들지만, 잘 모르겠습니다.😅😅 어떤 측면해서 차이를 고려해 봐야할까요???

2021-03-12 10:45 UTC, ellyheetov commented on VendingMachineApp/Model/Money.swift
>      private(set) var coins : Int
Int가 아닌 Money객체를 이용하여 상호작용을 할 수 있어야 한다는 말씀이신가요???

2021-03-12 10:50 UTC, ellyheetov commented on VendingMachineApp/View/StockStackView.swift
>          }
`setStockCells`는 초기 화면을 그릴 때, (버튼, 이미지, 라벨)을 구성하는 코드입니다.
`setStocksCount`는 vendingmachine에 재고에 변경사항이 있을 때 호출되는 함수로써 label만 다시 재 구성하여 화면에 보여지게 됩니다.

2021-03-12 10:51 UTC, ellyheetov commented on VendingMachineApp/View/UIBeverageButton.swift
> +        setUpButton()
구체적인 하위 타입을 가지고 있는 것이 어떤 경우에 안 좋을 수 있나요???

2021-03-12 10:57 UTC, ellyheetov commented on VendingMachineApp/View/UICoinButton.swift
> +        self.setTitle(title, for: .normal)
1000원을 추가하는 버튼과, 5000원을 추가하는 버튼을 초기 생성 시 지정하기 위해 title을 넘겨 주었습니다. 
한 번 생성 이후에 값이 변경될 일이 없기 때문에, 생성 시 초기값을 넘겨 주어도 된다고 판단하였습니다.

2021-03-12 11:13 UTC, ellyheetov commented on VendingMachineApp/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateCoinLabel), name: .CoinChanged, object: nil)
post하는 객체는 vendingmachine인데, object에 vendingmachine을 넣으면 원하는대로 notification이 오지 않습니다. 혹시 이유를 알수 있을 까요????

2021-03-12 11:14 UTC, ellyheetov commented on VendingMachineApp/Model/Beverage.swift
> +    }
미처 생각하지 못했네요. 브랜드, 용량, 가격, 이름이 모두 같아야 같은 인스턴스가 되도록 하였습니다.

2021-03-12 11:17 UTC, ellyheetov commented on VendingMachineApp/View/UIBeverageButton.swift
> +        self.addTarget(superview, action: #selector(ViewController.appendBeverageToMachine), for: .touchDown)
view controller에서 button을 연결하고 싶었지만, 여러 stackview 안에 속해 있는 button이다보니, 외부에서 연결하는것이 어려워졌습니다. 현재 addTarget에서 superview를 연결하면 여전히 강한 결합이 유지되는 거죠? 이렇게 강한 결합이 발생하는 것을 어떻게 디버깅 할 수 있나요??

2021-03-12 11:18 UTC, ellyheetov commented on VendingMachineApp/ViewController.swift
> +        NotificationCenter.default.post(name: .StockCountChanged, object: nil)
Observer하는 객체는 ViewController, post하는 객체는 VendingMachine 인거죠?

2021-03-12 11:21 UTC, ellyheetov commented on VendingMachineAppTests/VendingMachineAppTests.swift
> +        expectDict.removeValue(forKey: ObjectIdentifier(Georgia.Type.self))
각 메소드에 대한 테스트 이후에 특정한 시나리오 대로 동작하는 지 확인하고자, 여러개의 테스트를 하나의 test 함수에서 돌리게 되었습니다. 확실히 unit 테스트는 아니죠..ㅎㅎ

2021-03-12 13:36 UTC, ellyheetov commented on VendingMachineApp/Model/DataManager.swift
> +        } catch {
사실 고민했던 부분입니다. 기존 데이터를 저장해야 한다면 음료의 배열을 저장 하는 것을 먼저 생각하였습니다. 

자판기 자체를 저장하는 경우 자판기 인스턴스 내부에 있는 재고와 돈에 대한 데이터 모두를 인코딩/디코딩 해야하기 때문에 더 많은 오버헤드가 발생할 것으로 예상했습니다. 때문에 자판기 자체보다는 음료의 배열을 저장하는게 더 효율적이라 생각하게 되었습니다.

하지만, 깊은 복사의 copy()를 알아보고 다른 생각을 하게 되었습니다. 
- 데이터를 저장하는 과정에서 자판기 자체는 깊은 복사를 하지만, 내부 데이터들은 얕은 복사가 이뤄지는 것이 아닐까? 
- 만약 자판기 자체를 저장하는 것이 아닌 음료 배열을 저장하게 된다면, 모든 음료들에 대하여 깊은 복사 과정을 거쳐 더 많은 메모리를 사용하게 되는 것이 아닐까?

하는 생각을 하게 되었습니다. 데이터가 아카이빙 되는  코드를 직접 보면 좋겠지만, 내부 코드는 디버깅이 안되는 것 같아서, 이상 저의 생각이었습니다..ㅎ

2021-03-15 05:37 UTC, godrm commented on VendingMachineAppTests/VendingMachineAppTests.swift
> +        expectDict.removeValue(forKey: ObjectIdentifier(Georgia.Type.self))
아하 네 그런 맥락이라면 잘하셨어요. 그렇더라도 시나리오 전체를 하면 안되고, 시나리오도 유스케이스 단위 정도로 나눠주는 게 좋습니다.

2021-03-15 05:38 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateCoinLabel), name: .CoinChanged, object: nil)
post하는 sender도 살펴보세요. 거기에서 object를 지정해줘야 같이 매칭이 됩니다.

2021-03-15 05:38 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        NotificationCenter.default.post(name: .StockCountChanged, object: nil)
그렇죠!

2021-03-15 05:39 UTC, godrm commented on VendingMachineApp/View/UICoinButton.swift
> +        self.setTitle(title, for: .normal)
네. 그렇지만 Label도 항상 그렇지 않을 수 있습니다.
뷰의 표시는 설정에서 언어나 지역, 포맷 등을 바꾸면 다시 바뀌는 경우도 많아요. 
뷰의 값이 한 번만 지정되는 경우도 있지만, 매번 바뀌도록 하는 경우도 꽤 많습니다. 참고하세요.

2021-03-15 05:42 UTC, godrm commented on VendingMachineApp/View/UIBeverageButton.swift
> +        self.addTarget(superview, action: #selector(ViewController.appendBeverageToMachine), for: .touchDown)
ViewController에 [StackView ( Button )] 이렇게 여러 스택뷰가 있다는 의미인거죠?
Button은 자신이 속한 상위 뷰인 스택뷰를 Target으로 지정하고, 
스택뷰는 뷰 컨트롤러에 알려주고, 뷰 컨트롤러는 스택뷰를 구분해서 특정 음료수를 매칭하는 구조는 어떨까요?

2021-03-15 05:46 UTC, godrm commented on VendingMachineApp/AppDelegate.swift
>          return true
객체 생성과 메소드 호출되는 시점들을 잘 이해하면 됩니다. 
주의할 점은 자판기 인스턴스가 여러번 생기는지, 그래서 여기저기 다른 객체가 다른 인스턴스를 참조하지는 않는지 살펴보면 됩니다.

2021-03-15 06:10 UTC, godrm commented
모두 수정해서 반영한 상태인가요?

2021-03-15 06:12 UTC, ellyheetov commented on VendingMachineApp/ViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateCoinLabel), name: .CoinChanged, object: nil)
아하! post하는 sender에 자기자신(vendingmachine.self)을 넣어주고, obsever 등록 시에 sender에도 vendingmachine을 넣어 해결하였습니다.😆

2021-03-15 06:12 UTC, ellyheetov commented
아직 수정하고 있습니다. 다시 댓글 달도록 할게요!ㅎㅎ

2021-03-15 06:15 UTC, ellyheetov commented on VendingMachineApp/AppDelegate.swift
>          return true
가장 처음 앱이 시작 될 때에만 자판기의 생성자 메소드가 불리고, 다시 재 시작시에는 자판기의 생성자가 새로 생성되지 않는 것을 확인하였습니다.

2021-03-15 06:55 UTC, ellyheetov commented on VendingMachineApp/View/UIBeverageButton.swift
> +        self.addTarget(superview, action: #selector(ViewController.appendBeverageToMachine), for: .touchDown)
이해는 가지만, 구체적으로 어떻게 코드를 짜야할지 아직 감이 오지 않습니다...ㅎㅎ

그리고 target으로 `superview`를 넣어놨지만, 이 값은 현재 `nil`이고 UIBeverageButton이 생성 된 이후, 다른 view 내에 들어가야지만 `superview`가 생기는 것 같네요. 때문에 해당 버튼에는 target이 없는 거구요.

이러한 방식이라면 target-action은 `setUpButton()` 내에서가 아닌 외부에서 지정해주어야 할 것 같아요. 

> 버튼 설정은 내부에서 하고, 연결은 외부에서 하는 것도 괜찮습니다.

해당 코멘트가 이런 맥락이겠죠?

2021-03-15 06:57 UTC, ellyheetov commented on VendingMachineApp/View/UICoinButton.swift
> +        self.setTitle(title, for: .normal)
그런 상황은 있을 수 있군요! 수정하는게 좋을 것 같네요.

2021-03-15 07:01 UTC, godrm commented on VendingMachineApp/View/UIBeverageButton.swift
> +        self.addTarget(superview, action: #selector(ViewController.appendBeverageToMachine), for: .touchDown)
네. 맞아요. 그래서 superview 같은 속성에 의존하도록 하면 안됩니다. 
버튼을 생성하고 상위(지금은 스택뷰겠네요) target-action을 지정해주는 게 좋습니다.
그리고 스택뷰는 그걸 받아서 상위에 ViewController에 전달해주는거죠. 
이 때는 target-action 이 아니라 다른 방법도 괜찮습니다.

2021-03-15 07:05 UTC, ellyheetov commented
# 수정사항
- vendingmachine 초기화 지점 변경 : didFinishLaunchingWithOptions → willFinishLaunchingWithOptions
- Notification Name을 extension → VendingMachine Nested 변수로 변경
- Notification sender, post 객체 지정
- Beverage Equatable 변경
- isExpired() : 순수 함수로 만들기 위해 매개변수를 받는 구조로 변경
- isHot() : 인스턴스 온도 값과 객체 내 기준 값을 비교하여 결과 반환 → 인스턴스의 온도 값과 매개변수로 넘어오는 온도 값을 비교하여 결과 반환
- label의 title : title string을 가지고 생성 → 생성 이후 title을 변경하도록 수정

# 해결하지 못한 부분
- 강제 Unwrapping을 다음과 같이 제거 하고자 했으나 해당 에러로 제거하지 못하였습니다. 

Before
  
  ```
  required init?(coder: NSCoder) {
      self.kind = Kind(rawValue: coder.decodeObject(forKey: "TopKind") as! String)!
      super.init(coder: coder)
  }
  ```
  After
  ```
  required init?(coder: NSCoder) {       // 'self' used before 'super.init' call
      guard let value = coder.decodeObject(forKey: "TopKind") as? String else { return }
      guard let kind = Kind(rawValue: value) else { return }
      self.kind = kind
      super.init(coder: coder)
  }
  ```
Error Message : 'self' used before 'super.init' call

2021-03-15 07:14 UTC, ellyheetov commented
# 수정사항
- vendingmachine 초기화 지점 변경 : didFinishLaunchingWithOptions → willFinishLaunchingWithOptions
- Notification Name을 extension → VendingMachine Nested 변수로 변경
- Notification sender, post 객체 지정
- Beverage Equatable 변경
- isExpired() : 순수 함수로 만들기 위해 매개변수를 받는 구조로 변경
- isHot() : 인스턴스 온도 값과 객체 내 기준 값을 비교하여 결과 반환 → 인스턴스의 온도 값과 매개변수로 넘어오는 온도 값을 비교하여 결과 반환
- label의 title : title string을 가지고 생성 → 생성 이후 title을 변경하도록 수정

# 해결하지 못한 부분
- 강제 Unwrapping을 다음과 같이 제거 하고자 했으나 해당 에러로 제거하지 못하였습니다. 

Before
  
  ```
  required init?(coder: NSCoder) {
      self.kind = Kind(rawValue: coder.decodeObject(forKey: "TopKind") as! String)!
      super.init(coder: coder)
  }
  ```
  After
  ```
  required init?(coder: NSCoder) {       // 'self' used before 'super.init' call
      guard let value = coder.decodeObject(forKey: "TopKind") as? String else { return }
      guard let kind = Kind(rawValue: value) else { return }
      self.kind = kind
      super.init(coder: coder)
  }
  ```
Error Message : 'self' used before 'super.init' call
- setTitle이 동작 하지 않음
```swift
self.setTitle("추가하기", for: .normal)
```
추가하기 버튼에 대한 title, 동전 금액에 대한 title 모두 동작하지 않습니다.

2021-03-15 07:18 UTC, godrm commented
> # 수정사항
> * vendingmachine 초기화 지점 변경 : didFinishLaunchingWithOptions → willFinishLaunchingWithOptions
> * Notification Name을 extension → VendingMachine Nested 변수로 변경
> * Notification sender, post 객체 지정
> * Beverage Equatable 변경
> * isExpired() : 순수 함수로 만들기 위해 매개변수를 받는 구조로 변경
> * isHot() : 인스턴스 온도 값과 객체 내 기준 값을 비교하여 결과 반환 → 인스턴스의 온도 값과 매개변수로 넘어오는 온도 값을 비교하여 결과 반환
> * label의 title : title string을 가지고 생성 → 생성 이후 title을 변경하도록 수정
> 
> # 해결하지 못한 부분
> * 강제 Unwrapping을 다음과 같이 제거 하고자 했으나 해당 에러로 제거하지 못하였습니다.
> 
> Before
> 
> ```
> required init?(coder: NSCoder) {
>     self.kind = Kind(rawValue: coder.decodeObject(forKey: "TopKind") as! String)!
>     super.init(coder: coder)
> }
> ```
> 
> After
> 
> ```
> required init?(coder: NSCoder) {       // 'self' used before 'super.init' call
>     guard let value = coder.decodeObject(forKey: "TopKind") as? String else { return }
>     guard let kind = Kind(rawValue: value) else { return }
>     self.kind = kind
>     super.init(coder: coder)
> }
> ```
> 
> Error Message : 'self' used before 'super.init' call
> 
> * setTitle이 동작 하지 않음
> 
> ```swift
> self.setTitle("추가하기", for: .normal)
> ```
> 
> 추가하기 버튼에 대한 title, 동전 금액에 대한 title 모두 동작하지 않습니다.

둘 다 같은 맥락이네요. self는 super.init을 호출하기 전에는 사용할 수 없으니까요.
결국 init()에서 이어지는 동작들인데, decode 실패할 경우처럼 초기값을 주어야 하는 경우도 있습니다. 
setTitle도 아직 self가 안전하게 확인되지 않아서 인거죠. 생성 이후에 설정이 필요하다고 생각하면 됩니다.

2021-03-15 07:19 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
> +        return money.resetCoins()
이 메소드 이상한건가요? return 인가요? reset 인가요?

2021-03-15 07:20 UTC, merged

2021-03-15 07:23 UTC, ellyheetov commented on VendingMachineApp/Model/VendingMachine.swift
> +        return money.resetCoins()
현재 사용되고 있는 메소드는 아닙니다.

사용자가 자판기에 넣은 돈은 반환 받고 싶은 경우, 
- 자판기에서 돈을 반환
- 현재 자판기가 가지고 있는 돈을 0원으로 초기화

두 가지 역할을 하는 메소드 입니다.

한 메소드 내에서 여러 행동을 하다보니 조금 이상해 졌네요ㅎㅎ

2021-03-15 07:25 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
> +        return money.resetCoins()
아하 네. 이름만보고 동작이 이상한건가 했어요. 이해했습니다.