Ray step7
code-squad/swift-vendingmachineapp pull request #323
Opened 2021-03-17 06:08 UTC by torch-ray

## Step6 작업목록
- [x] 재고추가 버튼 이동 user VC -> Admin VC 
- [x] 스토리보드로 segue활용하여 VC이동 구현
- [x] Admin VC UI는 코드로 구현
- [x] 실행화면 추가

## 학습키워드
- UIButton & UIImageView
- UI 코드 구현

## 고민과 해결
- UIButton을 UIImageView 위에 구현했을 때, 버튼이 눌리지 않는 현상
- 뷰디버깅 통해 superView bounds 밖으로 버튼이 나가있는 것 발견하고 수정
- 여전히 버튼 동작하지 않음
- UIImageView가 superView인 경우 subViews까지 enable = false인 것을 확인
- 슈퍼뷰를 UIView로 수정하여 해결

## 부연설명

- Admin VC를 코드로 구현하였습니다.
- 재고추가에 따라 Label의 값을 수정하는 방식이 어려웠습니다.

## 질문거리
- 관리자 화면에서 재고추가시 label값을 update하기 위해 StockView를 만들 때마다 label을 배열에 넣고, 재고추가시 [UILabel]배열을 for-loop로 탐색하면서 update해줬습니다. 다른 방식은 어떻게 가능할지 감이오지 않습니다 ㅠㅠ

2021-03-17 07:50 UTC, godrm requested changes
수고하셨습니다. 다음 피드백 내용을 확인해서 개선해보죠.
PR 열어놓을게요.

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +    private var vendingMachine = VendingMachine.sharedInstance()
자판기 싱글톤에 접근하는 것보다는
자판기에서 Admin만 쓰는 프로토콜로 의존성을 주입해주도록 개선해보세요.

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +        beverageStackView = AdminBeverageStackView()
내부 속성이고 내부 메소드라면 AdminBeverageStackView에서 beverageStackView를 설정해도 되는거 아닌가요?

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateBeverageStock(_:)), name: VendingMachine.updateBeverages, object: nil)
object는 sender의미로 지정하는 게 더 좋습니다.

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +            beverageStockList[index].text = "\(vendingMachine.beverages.stockOfEach(beverage: beverageList[index]))개"
이 메소드는 label 전체를 모두 업데이트 하는건가요?
재고 추가할 때는 어느 하나만 바뀌지 않던가요?

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +}
extension으로 구분한 이유는 뭔가요? 서로 다른 맥락을 가지는 메소드라면 그 의도를 표현해보세요. extension을 나누는 것 말고 명시적으로 표현할 수 있는 방법은 없을까요?

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +        let beverage = vendingMachine.typeToInstance(product: sender.beverageType)
sender.beverateType이 타입 정보인가요? 이게 그냥 인스턴스 생성이라면 자판기가 하지 않고 팩토리에서 해야 하는거 아닌가요? 
음료 인스턴스 생성과 음료 인스턴스 관리를 다른 타입에서 분리해야 하는거 아닐까요?

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/InsertedMoney.swift
> +        NotificationCenter.default.post(name: VendingMachine.updateInsertedMoney, object: self, userInfo: nil)
VendingMachine.updateBeverages나 VendingMachine.updateInsertedMoney 노티를 보내는 객체가
하위에 Beverages랑 InsertedMoney네요. 그러면 post할 때 sender(object)에 self를 넣기 때문에 자판기가 보내는 게 아니네요.
분명 notification 정의는 `VendingMachine.updateInsertedMoney` 처럼 자판기의 노티인데 다른 객체가 보내는 노티가 됩니다. 
하위 객체가 직접 보내는게 좋을까요? 아니면 `afterBuyingProduct(minus:)`를 호출한 자판기 코드에서 post하는게 좋을까요?

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: Cantata.self)
이 메소드들도 합쳐서 한꺼번에 다형성으로 처리할 방법은 없을까요?

2021-03-17 07:50 UTC, godrm commented on VendingMachineApp/VendingMachineApp/View/AddBeverageButton.swift
> +    var beverageType: Beverage.Type!
버튼(혹은 뷰)이 세부 타입을 포함하고 public var로 갖고 있는 것은 좋은 선택이 아닙니다.
어떤 버튼이 눌렸을 때 어떤 음료수 타입과 관련이 있는지는 뷰 컨트롤러 수준에서만 알고 있는 게 좋습니다.
뷰 자체는 하위 타입, 하위 값들과 관련이 없도록 하는게 좋습니다.

2021-03-17 09:01 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +}
extension으로 이벤트를 처리하는 메서드, configure을 담당하는 메서드 이런식으로 나눠서 묶어놨습니다. 명시적으로 표현할 수 있는 방법이면 주석으로 설명을 다는 것일까요 ㅠㅠ?

2021-03-17 09:02 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/InsertedMoney.swift
> +        NotificationCenter.default.post(name: VendingMachine.updateInsertedMoney, object: self, userInfo: nil)
그렇게되면 addBeverage메서드가 NotificationCenter를 3개를 갖고있게되서 나눴는데... 그렇다면 addBeverage메서드를 더 작게 나눠서 vendingMachine에서 NotificationCenter를 분산할 수 있도록 수정해야할까요? 뭔가 메서드를 나누지 않고도 NotificationCenter를 하나만 가지도록 할 수 있는 방법을 고민하고 있습니다 ㅠㅠ

2021-03-17 09:19 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: Cantata.self)
지금과 같이 스토리보드로 구현한 경우도 가능할까요? Admin VC처럼 코드로 구현하면 가능한데... 스토리보드로도 가능하다면 혹시 진행방향에 대해 힌트를 주실 수 있을까요?

2021-03-17 09:28 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +        beverageStackView = AdminBeverageStackView()
엇... stackView를 뷰컨트롤러에 띄우기 위해서 인스턴스로 만든건데(configrue을 뷰컨트롤러의 view를 기준으로 하려고), 혹시 피드백이 어떤 의미인건지 조금 더 설명해주실 수 있을까요 ㅠㅠ?

2021-03-17 09:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +        beverageStackView = AdminBeverageStackView()
아.. 생성해서 return 하는거군요. 
AdminBeverageStackView()에서 생성도 하고 beverageStackView에도 넣는 메소드도 있으면 좋겠다 정도입니다.

2021-03-17 09:46 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +}
extension 문법 중에 한 번 찾아보세요.

2021-03-18 05:22 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +    private var vendingMachine = VendingMachine.sharedInstance()
다음스텝에서 코어그래픽스 구현하고 수정해보겠습니다! 그런데 혹시, 프로토콜로 객체간 의존성을 낮추면 반대로 프로토콜에 대한 의존성이 높아지는 문제가 생기는 건 어떻게 해결이 가능할까요...?

2021-03-18 05:22 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +        NotificationCenter.default.addObserver(self, selector: #selector(updateBeverageStock(_:)), name: VendingMachine.updateBeverages, object: nil)
수정하였습니다!

2021-03-18 05:22 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +            beverageStockList[index].text = "\(vendingMachine.beverages.stockOfEach(beverage: beverageList[index]))개"
하나만 바뀌도록 수정하였습니다!

2021-03-18 05:23 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +}
extension문법을 찾아봐도 기능별로(?) extension을 분리하는 것 외에 마땅히 방법을 찾지 못했습니다 ㅠㅠ 혹시 추가적인 검색 키워드가 있을까요?

2021-03-18 05:23 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +        let beverage = vendingMachine.typeToInstance(product: sender.beverageType)
버튼에서 type을 제거하면서 수정하였습니다.

2021-03-18 05:23 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/InsertedMoney.swift
> +        NotificationCenter.default.post(name: VendingMachine.updateInsertedMoney, object: self, userInfo: nil)
수정하였습니다!

2021-03-18 05:23 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/View/AddBeverageButton.swift
> +    var beverageType: Beverage.Type!
제거하고 수정하였습니다!

2021-03-18 05:56 UTC, godrm commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +}
//MARK:-- 를 넣는 방법도 있는데 이런 typealias를 쓰는 방법도 있습니다.
무조건 extension을 나누기 보다는 맥락이 있으면 더 좋을 것 같습니다. 
https://www.natashatherobot.com/swift-how-to-name-your-extensions/

2021-03-18 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/Model/InsertedMoney.swift
> +        NotificationCenter.default.post(name: VendingMachine.updateInsertedMoney, object: self, userInfo: nil)
사실 3가지 변화가 일어나는 거니까요. 각각 있는게 맞죠. 보는 대상이 누구냐인거는 고민해볼 문제죠. 
3가지 변화를 각기 표현하는 대상이 다를수도 있으니까요.

2021-03-18 05:58 UTC, godrm commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: Cantata.self)
스토리보드에서도 Action을 하나에 지정할 수 있지 않나요? 그러면 sender로 구분할 수 있죠

2021-03-18 06:04 UTC, godrm commented
모두 수정완료한 상태인가요? 작업중인가요?

2021-03-18 06:10 UTC, torch-ray commented
> 모두 수정완료한 상태인가요? 작업중인가요?

추가로 주신 피드백 확인하고 수정하여 다시 push하겠습니다!

2021-03-18 06:49 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/VendingMachineViewController.swift
> +        vendingMachine.buyBeverage(product: Cantata.self)
하나의 action에 지정하고 수정하였습니다!

2021-03-18 06:50 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/Model/InsertedMoney.swift
> +        NotificationCenter.default.post(name: VendingMachine.updateInsertedMoney, object: self, userInfo: nil)
앞으로도 수정방향은 메서드를 최대한 작게 나누고 각 메서드에 하나의 NotificationCenter만 들어가도록 방향을 설계해보겠습니다.

2021-03-18 06:51 UTC, torch-ray commented on VendingMachineApp/VendingMachineApp/AdminViewController.swift
> +}
감사합니다! Private typealias는 아직 생각해볼 여지가 ㅇ있는 것 같습니다.. 흠... 댓글에서처럼 뭔가 코드의 가독성이 정말 더 좋아지는가? 오히려 헷갈리게 만드는거너 아닌가에 대해 확신이 없습니다

2021-03-18 06:51 UTC, torch-ray commented
전체 수정완료했습니다!

2021-03-18 06:54 UTC, godrm commented
수고하셨습니다. 전체적으로 개선해보거나 step8까지 한 번 도전해보세요.

2021-03-18 06:54 UTC, merged