[Elly] Step7
code-squad/swift-vendingmachineapp pull request #329
Opened 2021-03-18 09:04 UTC by ellyheetov

# 프로그래밍 요구사항
- [x] 스토리보드에서 Button을 추가하고, Attributes에서 Type을 Info Light로 설정한다.
- [x] 새로운 ViewController를 옆에 추가하고, Button에서 Segue를 연결한다.
- [x] Segue를 선택하고 Kind를 Present Modally로 지정하고, Transition을 Flip Horizontal로 설정한다.
- [x] 자판기에 음료수를 관리하는 관리자 기능(AdminMode)과 음료를 구매하는 사용자 기능(UserMode)을 담당하는 객체를 분리한다.
- [x] 새롭게 추가한 화면을 관리자 모드로 동작하도록 개선한다.
- [x] 이미지와 재고 추가 버튼을 복사해서 관리자 화면으로 복사하고, 동작하도록 코드를 수정한다.
- [x] 재고 추가 버튼은 기존 화면에서 삭제한다.
- [x] 관리자 화면에 [닫기] 버튼을 추가하고, 버튼을 누르면 dissmiss()를 호출한다.
- [x] 다른 동작은 이전 단계와 동일하게 동작해야 한다.

# 고민
음료의 타입과 이미지를 매칭하는 부분을 딕셔너리 구조로 변경하려고 했으나 해결하지 못하였습니다. 파라미터로 `Beverage.Type `자료형의 값(예를 들어 `Top.self`)을 넘겨주고, ObjectIdentifier를 적용하기 위해서 `type(of: parameter)`를 하면 `Top.Type`이 아닌 `Beverage.Type`이 반환되었습니다. 때문에 모든 음료수에 대하여 Beverage.Type을 리턴하게 되어 딕셔너리 구조로 변경하지 못하였습니다.

2021-03-18 09:25 UTC, godrm requested changes
수고하셨습니다. 프로토콜을 분리해놓고 활용을 못하고 있는 것 같습니다.
PR 열어놓을테니 개선해보세요.

2021-03-18 09:25 UTC, godrm commented on VendingMachineApp/AdminViewController.swift
> +    }()
ViewController로 주입이 가능하니까 구체 타입에 의존하지 않고, private var로 선언하는 게 좋습니다.
예를 들어 자판기를 사용한다면 AdminViewController에서 사용하는 메소드들을 프로토콜로 지원하는거죠.
`인터페이스를 분리한다` 측면을 고려해보세요. 

----

써놓고 아래를 살펴보니 이미 프로토콜로 분리했네요. 하지만 여기서는 여전히 구체타입을 쓰고 있습니다.
프로토콜을 나눴으면 그것을 타입으로 적극 활용해보세요.

2021-03-18 09:25 UTC, godrm commented on VendingMachineApp/AdminViewController.swift
> +        closeButton.frame = CGRect(x: view.bounds.maxX - 40, y: view.bounds.minY + 20, width: 20, height: 20)
viewWillAppear 에 있는 코드들이 추상화 수준이 비슷한가요? 여러 부분으로 나눠져 있다면 내부 함수로 분리해보는 것도 고려해보세요.

2021-03-18 09:25 UTC, godrm commented on VendingMachineApp/AdminViewController.swift
> +    func stockStackViewConfiguration(){
MARK:--를 넣는 방법도 있지만 이런 방법도 있습니다. https://www.natashatherobot.com/swift-how-to-name-your-extensions/
참고하세요.

2021-03-18 09:25 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
>      }
이 메소드들은 분리한 프로토콜에서 어디에도 속하지 않는건가요? 그런 메소드가 있을 수 있나요?
사용자도 안쓰고, 관리자고 안쓰는 메소드가 있으면 이상한게 아닐까요?

2021-03-18 09:25 UTC, godrm commented on VendingMachineApp/View/OneStockView.swift
> +        addButton.addTarget(superview, action: #selector(AdminViewController.appendBeverageToMachine), for: .touchDown)
이 부분도 뷰가 AdminViewController을 직접 알고 있어야 하니까 좋은 구조는 아닙니다.
그래서 AdminViewController -> OneStockView -> AddButton 순서대로 target-action을 추가해줘야 하위에서 상위를 모르고 동작할 수 있게 됩니다. 오늘 수업에서 bind() 동작을 떠올려보세요.

2021-03-18 09:25 UTC, godrm commented on VendingMachineApp/View/UIBeverageButton.swift
> +        self.addTarget(superview, action: #selector(AdminViewController.appendBeverageToMachine), for: .touchDown)
여기도 마찬가지 입니다. 직접 뷰컨트롤러 타입을 알고 있어야 한다는 것은 유연한 구조가 아닌거죠.

2021-03-18 09:25 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        vendingMachine = (UIApplication.shared.delegate as! AppDelegate).vendingMachine
뷰 컨트롤러에서 상위 타입인 앱 델리게이트 속성에 접근하기 보다는, 여기서 필요한 프로토콜 타입형태로 선언하고
앱 델리게이트에서 주입하는 방식으로 구현해보세요.

2021-03-18 09:25 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        stockStackView.stockCells.forEach{ $0.addButton.isHidden = true}
`stockStackView.stockCells.forEach{ $0.addButton.isHidden = true}` 이런 코드는 
StockStackView.setUp() 내부에 있어도 되는게 아닐까요?

2021-03-19 06:17 UTC, ellyheetov commented on VendingMachineApp/ViewController.swift
> +        vendingMachine = (UIApplication.shared.delegate as! AppDelegate).vendingMachine
앱 델리게이트에서 주입한다는 말이 무슨말인지 모르겠습니다.😭

2021-03-19 06:17 UTC, ellyheetov commented on VendingMachineApp/View/OneStockView.swift
> +        addButton.addTarget(superview, action: #selector(AdminViewController.appendBeverageToMachine), for: .touchDown)
수업에서 예시로 보여주신 bind를 참고하여 수정하였습니다.

2021-03-19 06:17 UTC, ellyheetov commented on VendingMachineApp/Model/VendingMachine.swift
>      }
그렇게 볼 수 있겠네요. 자판기가 가지고 있는 모든 함수를 분리한 프로토콜에 속하도록 수정하였습니다.

2021-03-19 06:17 UTC, ellyheetov commented on VendingMachineApp/AdminViewController.swift
> +    func stockStackViewConfiguration(){
오. 이런건 몰랐네요. 감사합니다.

2021-03-19 06:17 UTC, ellyheetov commented on VendingMachineApp/AdminViewController.swift
> +        closeButton.frame = CGRect(x: view.bounds.maxX - 40, y: view.bounds.minY + 20, width: 20, height: 20)
넵. 내부함수로 분리해 보겠습니다.

2021-03-19 06:17 UTC, ellyheetov commented on VendingMachineApp/AdminViewController.swift
> +    }()
구체타입에 의존하지 않고 프로토콜을 사용한다는 말이 VendingMachine 구체타입을 통째로 가져오는 것이 아닌 관리자와 관련된 부분만 가져도 된다는 말씀이신가요??

현재 제 코드에서 AdminViewController로 말하자면, AdminOfVendingMachine 프로토콜을 가지고 와야하는건가요???
`private var vendingMachine : AdminOfVendingMachine!` 이렇게요.

2021-03-19 06:21 UTC, godrm commented on VendingMachineApp/ViewController.swift
> +        vendingMachine = (UIApplication.shared.delegate as! AppDelegate).vendingMachine
rootViewController를 찾아서 거기서 setXXX()하는거죠.

2021-03-19 06:22 UTC, godrm commented on VendingMachineApp/AdminViewController.swift
> +    }()
넵 그렇습니다 :) 그래야 뷰 컨트롤러는 내부에서 쓰는 프로토콜에만 의존하는거죠.

2021-03-19 06:30 UTC, ellyheetov commented on VendingMachineApp/ViewController.swift
> +        stockStackView.stockCells.forEach{ $0.addButton.isHidden = true}
# 수정사항
- Button이 BeverageType값을 가지고 있음 → Button은 내부에 음료 타입을 가지고 있지 않으며, `bind(handler:)`함수를 통해 외부에서 action을 지정하도록 수정
- VendingMachine을 사용자 프로토콜과 관리자 프로토콜로 분리, vendingMachine을 사용하는 ViewController는 해당 프로토콜을 가짐
- OneStockCell은 추가하기 버튼과 구매하기 버튼을 가지고 있어, 조건에 따라 하나의 버튼만 보여줌 → OneStockCell은 하나의 button을 가진다. 초기화시 '구매하기' 또는 '추가하기' 버튼을 선택하여 생성하도록 수정

# 고찰
- 네이밍도 수정하려고 했으나, 직관적으로 알아볼수 있는 변수명이 떠오르지 않아 남겨둠
- StackView의 제약조건을 지정하였음에도 내부에 View가 지정된 영역을 벗어남
<img width="400" alt="Screen Shot 2021-03-19 at 3 04 02 PM" src="https://user-images.githubusercontent.com/60229909/111738250-58d12080-88c4-11eb-8b9c-6721dec8716e.png">

# 🙋🏻‍♀️ 질문
- [Beverage.type : String] 자료를 만들어 UIImage 매칭 하는 부분에 대해 조언을 받을 수 있을까요?
    ```
    print(currentType) // Top
    print(type(of: currentType.self))   // Beverage.Type     
    print(type(of: Top.self))    // Top.Type
    ```


### 🧐 혹시 수정이 더 필요하다면 PR 닫지 말아주세요.🤔

2021-03-19 06:30 UTC, ellyheetov commented
# 수정사항
- Button이 BeverageType값을 가지고 있음 → Button은 내부에 음료 타입을 가지고 있지 않으며, `bind(handler:)`함수를 통해 외부에서 action을 지정하도록 수정
- VendingMachine을 사용자 프로토콜과 관리자 프로토콜로 분리, vendingMachine을 사용하는 ViewController는 해당 프로토콜을 가짐
- OneStockCell은 추가하기 버튼과 구매하기 버튼을 가지고 있어, 조건에 따라 하나의 버튼만 보여줌 → OneStockCell은 하나의 button을 가진다. 초기화시 '구매하기' 또는 '추가하기' 버튼을 선택하여 생성하도록 수정

# 고찰
- 네이밍도 수정하려고 했으나, 직관적으로 알아볼수 있는 변수명이 떠오르지 않아 남겨둠
- StackView의 제약조건을 지정하였음에도 내부에 View가 지정된 영역을 벗어남
<img width="400" alt="Screen Shot 2021-03-19 at 3 04 02 PM" src="https://user-images.githubusercontent.com/60229909/111738250-58d12080-88c4-11eb-8b9c-6721dec8716e.png">

# 🙋🏻‍♀️ 질문
- [Beverage.type : String] 자료를 만들어 UIImage 매칭 하는 부분에 대해 조언을 받을 수 있을까요?
    ```
    print(currentType) // Top
    print(type(of: currentType.self))   // Beverage.Type     
    print(type(of: Top.self))    // Top.Type
    ```

### 🧐 혹시 수정이 더 필요하다면 PR 닫지 말아주세요.🤔

2021-03-19 06:53 UTC, ellyheetov commented
엇! 빠진 부분이 있었네요. 다시 댓글 달도록 하겠습니다.

2021-03-19 07:07 UTC, ellyheetov commented
수정 완료하였습니다.

2021-03-19 07:15 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
>  }
프로토콜 선언도 다른 곳에 분리하는 것도 고려해보세요. 
왜냐하면 사용하는 곳이 다를테니까 파일에 대한 의존성이 생기지 않도록 분리하는 게 좋습니다.

2021-03-19 07:16 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
> +    //  자판기 금액을 원하는 금액만큼 올리는 메소드
주석은 코드내용보다 더 구체적이고 부가적인 정보를 주려고 사용하는 게 좋습니다.
코드로 유추가 가능한 정보를 다는 것은 의미없는 주석이 됩니다. 
함수 이름이나 변수명, 코드 흐름에 없는 내용을 주석으로 남기도록 습관을 가져보세요.

2021-03-19 07:17 UTC, godrm commented on VendingMachineApp/Model/VendingMachine.swift
> +        NotificationCenter.default.post(name: VendingMachine.CoinChanged, object: self)
이렇게 같은 노티가 서로 다른 곳에서 post할 때 구분할 필요는 없던가요?

2021-03-19 07:18 UTC, godrm commented on VendingMachineApp/UserViewController.swift
> +    }
여기 메소드들은 private 이라 private extension도 가능할 것 같네요.

2021-03-19 07:20 UTC, godrm commented on VendingMachineApp/View/UIBeverageButton.swift
> +        }
UIBeverageButton은 두고 하위에 각각 AddButton과 BuyButton으로 나누는게 낫을 수도 있겠습니다.
액션이 추상화된게 아니라 오히려 추상 데이터 타입이 되어버렸네요. 다형성의 잇점이 없어요. 
제가 보여준 예제는 버튼이 여러 일을 하는게 아니라, 버튼은 각자 일을 하고 동일한 역할을 하는 뷰모델이 있었던거죠.

2021-03-19 07:23 UTC, godrm commented
StackView 부분은 코드 diff 비교로는 알기 어려울 것 같습니다. 
이미지 뷰인가요? 버튼인가요? 혹은 버튼 내부의 이미지일까요?
뷰 제약사항을 연습하기 위해서 오토레이아웃을 적용해야 하는 시점이 다가오고 있습니다. 
아직 명시적으로 강제하고 있지 않지만 뷰를 디버깅하는 방식도 연습해보세요. frame 값을 찍어보고 왜 어느 시점에 틀어지는 지 예측해보세요.

2021-03-19 07:23 UTC, merged

2021-03-19 07:24 UTC, godrm commented
수정이 필요한 것 같지 않아서 머지했습니다 :)